### ISSUE TITLE
Nexus 4 Support

### ISSUE THREAD

**Issue by opssemnik** [efidroid/projectmanagement#104]
ARCH: APQ8064 (msm8960 branch)
BRANCH: LA.BF64 
OEM: lg
config.ini
`[variables]
DEVICE_NAME = Nexus 4
LK_TARGET = msm8960
LK_BASE = 0x0000000088f00000
LK_SOURCE = qcom/LA.BF64
BOOTIMG_BASE = 0x80200000
BOOTIMG_PAGESIZE = 2048
BOOTIMG_ADDITIONAL_ARGS = --ramdisk_offset 0x01600000
BOOTIMG_CMDLINE := console=ttyHSL0,115200,n8 androidboot.hardware=mako lpj=67677 user_debug=31
LCD_DENSITY = 320
LCD_VRAM_SIZE = 0x1000000
EDK2_BASE = 0x00000000fe000000
EDK2_SIZE = 0x0000000002000000`
and here it is my make
`EMMC_BOOT := 1
DISPLAY_2NDSTAGE_DTB := 1
DEBUG_ENABLE_UEFI_FBCON := 1
#DISPLAY_2NDSTAGE := 1
#DEFINES += WITH_2NDSTAGE_DISPLAY_DMA_TRIGGER
`
NON UEFI LK boots fine with display, fastboot all working.
UEFI LK boots fine however the display does a fade-out from the google logo and stays black forever, fastboot still works.
UEFI boot: i couldnt really test(because of display issue), but if i press volume down and power it goes into fastboot as EFIDroid. so i guess its working?

**Comment by M1cha** [comment]
LK_BASE was the problem (it probably conflicted with the framebuffer address)

**Comment by M1cha** [comment]
because the problem was fixed.
For whatever reason the device port never got official anyway.

That doesn't matter anymore though because all devices have to be ported from scratch now anyway.

**Comment by bam80** [comment]
@opssemnik, does the problem was fixed indeed?
