### ISSUE TITLE
Moto X 2014 support

### ISSUE THREAD

**Issue by chengyuhui** [efidroid/projectmanagement#105]
LK builds fine, but the device is not recognized on the computer when booting lk.img

conifg.ini
```ini
[variables]
DEVICE_NAME = Moto X 2014
LK_TARGET = msm8974
LK_BASE = 0x80208000
LK_SOURCE = qcom/LA.BF64
BOOTIMG_BASE = 0x80200000
BOOTIMG_PAGESIZE = 2048
BOOTIMG_ADDITIONAL_ARGS =  --ramdisk_offset 0x02000000 --tags_offset 0x01e00000
LCD_DENSITY = 424
BOOTIMG_DT_COMPRESSION = lz4
BOOTIMG_DT = $(DEVICE_DIR)/dt.img
```
lk_inc.mk
```makefile
EMMC_BOOT := 1
DISPLAY_2NDSTAGE := 1
DEFINES += WITH_2NDSTAGE_DISPLAY_DMA_TRIGGER
```

**Comment by feherneoh** [comment]
Something is off with your config.
Your LK_TARGET is Snapdragon 800/801, but your LK_BASE and BOOTIMG_BASE seem to be for Snapdragon S4
Try LK_BASE=0x00008000 and BOOTIMG_BASE=0x00000000

**Comment by M1cha** [comment]
@feherneoh he's using the initial config which uses the linux addr. but you're right, some devices don't like booting from there.

**Comment by chengyuhui** [comment]
Still nothing.. Both with and without `DEFINES += WITH_2NDSTAGE_DISPLAY_DMA_TRIGGER`

**Comment by feherneoh** [comment]
@micha I know, but still, the address is invalid.
SD800/801 uses 0x00000000 for bootimage, 0x00008000 for Linux.
0x80200000 and 0x80208000 are used by msm8960, msm8930, apq8064 and similar SoCs.

So it's not about using Linux or LK address, it's about using addresses of another SoC

**Comment by feherneoh** [comment]
Additional info: this phone has 2GB of RAM, so those addresses are outside of the available range
0x80000000 > 0x00000000-0x7FFFFFFF

**Comment by chengyuhui** [comment]
After checking in kernel source
```shell
CMDLINE="console=ttyHSL0,115200,n8 androidboot.hardware=bacon user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 androidboot.selinux=permissive"
BASE="0x00000000"
PAGESIZE="2048"
RAMDISK_OFFSET="0x02000000"
TAGS_OFFSET="0x01e00000"
```

**Comment by feherneoh** [comment]
That means I was right, and you are using invalid addresses. Did you create the config manually instead of using create_device?

**Comment by chengyuhui** [comment]
create_device.

**Comment by feherneoh** [comment]
Fix the addresses manually, then do an "rm -rf out" and build again

**Comment by chengyuhui** [comment]
Now I can boot into UEFI GUI but no ROM or recovery is shown (long press power button and select “Reboot to recovery" boots into the ROM)

**Comment by M1cha** [comment]
that's normal, just continue following the porting guide

**Comment by chengyuhui** [comment]
Now I have flashed the uefi_boot.img into my device.
But how can I continue with only "Fastboot" and "Reboot" options?

**Comment by z3ntu** [comment]
Create a ota server to use with the app. See https://github.com/efidroid/projectmanagement/wiki/%5BEFIDroid%5D-Porting-a-new-device#local-ota-server-for-using-efidroid-manager-with-a-new-device

**Comment by chengyuhui** [comment]
![sc](https://cloud.githubusercontent.com/assets/1381736/25304308/7207a1d8-2797-11e7-8182-b70230e80eff.png)
Internal OS and TWRP is recognized, bot not booting.

**Comment by chengyuhui** [comment]
And it gives me
```
[1] harry@arch-vm> diffatags atags                                                                                                                                                 
Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /memory/secure_region has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /memory/adsp_region has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /memory/qsecom_region has a reg or ranges property, but no unit name
FATAL ERROR: Couldn't open "/home/harry/efidroid/out/target/motorola/victara/lk_kernel/dtbpatched_out/*.dtb": No such file or directory
```
when trying to compare FDT patches

**Comment by chengyuhui** [comment]
[boot.zip](https://github.com/efidroid/projectmanagement/files/948963/boot.zip) contains the boot.img in case you need it.

**Comment by M1cha** [comment]
for build/:

`diff --git a/tools/diffatags b/tools/diffatags
index 2a1dd99f7..b9f18696f 100755
--- a/tools/diffatags
+++ b/tools/diffatags
@@ -15,9 +15,9 @@
 # limitations under the License.
 
 DTSOUT="$1"
-DTBPATCHOUT="$TOP/out/target/$EFIDROID_DEVICEID/lk_kernel/dtbpatched_out"
+DTBPATCHOUT="$TOP/out/device/$EFIDROID_DEVICEID/lk_kernel/dtbpatched_out"
 if [ -f "$DTBPATCHOUT" ];then
-    DTBPATCHOUT="$TOP/out/target/$EFIDROID_DEVICEID/lk_kernel/fdtpatched_out"
+    DTBPATCHOUT="$TOP/out/device/$EFIDROID_DEVICEID/lk_kernel/fdtpatched_out"
 fi
 
 set -e`

**Comment by chengyuhui** [comment]
result;
```
Warning (unit_address_vs_reg): Node /memory has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /memory/secure_region has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /memory/adsp_region has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /memory/qsecom_region has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc/qcom,smp2p-modem has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc/qcom,smp2p-adsp has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc/qcom,smp2p-wcnss has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc/rmtfs_sharedmem has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc/dsp_sharedmem has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc/mdm_sharedmem has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc/sound has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc/qcom,spmi@fc4c0000/qcom,pm8841@5/qcom,krait-regulator-pmic@2000 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc/qcom,avtimer has a reg or ranges property, but no unit name
Warning (unit_address_vs_reg): Node /soc/qcom,lpm-levels/qcom,cpu-modes/qcom,cpu-mode@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc/qcom,lpm-levels/qcom,cpu-modes/qcom,cpu-mode@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc/qcom,lpm-levels/qcom,cpu-modes/qcom,cpu-mode@2 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc/qcom,lpm-levels/qcom,cpu-modes/qcom,cpu-mode@3 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc/qcom,lpm-levels/qcom,system-modes/qcom,system-mode@0 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc/qcom,lpm-levels/qcom,system-modes/qcom,system-mode@1 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc/i2c@f9966000 has a unit name, but no reg property
Warning (unit_address_vs_reg): Node /soc/ti,c55-ctrl has a reg or ranges property, but no unit name
```

**Comment by chengyuhui** [comment]
I'm wondering if it's about LOKI (after looking in other issues)

**Comment by M1cha** [comment]
your log is perfectly fine now. the warnings are normal.
and LOKI is not yet supported.

**Comment by chengyuhui** [comment]
Any thoughts on the error message in screenshot?

**Comment by chengyuhui** [comment]
After looking into device tree, I think there shouldn't be LOKI……

2017年4月22日 21:06，"Michael Zimmermann" <notifications@github.com>写道：

**Comment by chengyuhui** [comment]
Can someone help me to examine that boot.img?

2017年4月26日 13:57，"Harry Cheng" <chengyuhui1@gmail.com>写道：
