### ISSUE TITLE
Moto G not detected in app

### ISSUE THREAD

**Issue by FireNX70** [efidroid/projectmanagement#109]
I've been searching through the repo and i've found that the Moto G (First Gen) seems to be ported, but the app said it didn't find a value and detected my phone as Motorola/falcon_umts.

Does the device not have a port or is it that the app hasn't been updated. If it's the latter, how do I install it without the app.

**Comment by z3ntu** [comment]
Motoral falcon isn't yet supported officially that's why the app doesn't find it.

**Comment by FireNX70** [comment]
Ok, thanks.
