### ISSUE TITLE
Nextbit Robin Port

### ISSUE THREAD

**Issue by AnierinBliss** [efidroid/projectmanagement#115]
So I started a little project to port Efi-Droid to my device and and upon booting into the nouefi lk.img my device wont show up in fast boot devices therefore cannot proceed to the next step of the porting process. 

Soc of device= msm8992
Screen density=480
kernel used=lineage OS

 any help would be awesome because our community really needs something like this 
![screenshot from 2017-06-28 01-08-34](https://user-images.githubusercontent.com/29746164/27621671-7c3242de-5ba0-11e7-9d11-eac2a3008cc1.png)

**Comment by M1cha** [comment]
first, using msm8994 is not a workaround because both msm8994 and msm8992 share the same base soc(cpu type, memory map, peripherals, ...).

AFAIK you have to use the correct LK_BASE for this soc. You can read it from a stock aboot dump.

**Comment by AnierinBliss** [comment]
alright I seem to have gotten it to work but it hangs on finalizing device. i'm assuming its because I need to add -i 0x2c3f to my fast boot command in order for it to interact properly

**Comment by M1cha** [comment]
It's weird that you have to do that because efidroid uses Googles USB vendor IDs instead of the one from the stock bootloader.

Either way you can just edit the script.

**Comment by AnierinBliss** [comment]
I've edited the script for finalize_device already and found two places where fastboot was used and i still get a hang..

**Comment by AnierinBliss** [comment]
![screenshot from 2017-06-28 04-28-35](https://user-images.githubusercontent.com/29746164/27627583-5465b032-5bba-11e7-9b62-27031fae4ee8.png)
 It's just hanging as I mentioned and I cant seem to get past it

**Comment by M1cha** [comment]
Did you try to manually run fastboot commands?
Maybe LK doesn't boot properly.

**Comment by AnierinBliss** [comment]
yeah manually running the command oem findbootimages works but i have no clue what to do with the output to be able to build uefi

**Comment by M1cha** [comment]
There are more occurrences of fastboot. Just grep through the build dir. I think fastboot wrapper is being used too

**Comment by AnierinBliss** [comment]
I also edited fast boot wrapper commands and tried to manually input them... Really at a wall here and im so close. if someone can upload edited scripts for me to use or explain more in depth..

heres an example of how i edited wrapper 

elif len(argv)>=1 and argv[0]=='boot-unpatched':
        rc = fastboot(['oem', 'setnvvar', 'fastboot-i 0x2c3f-enable-boot-patch', '0'])
        if rc:
            return rc
        argv = ['boot'] + argv[1:]

    elif len(argv)>=1 and argv[0]=='boot-patched':
        rc = fastboot(['oem', 'setnvvar', 'fastboot-i 0x2c3f-enable-boot-patch', '1'])

**Comment by AnierinBliss** [comment]
new issue has come up when building uefi

build.py...
: error 7000: Failed to execute command
make tbuild [/home/robin/repo/out/target/arm/uefiapp_LKL/Build/EFIDroidUEFIApps/DEBUG_GCC5/ARM/EFIDroidUEFIApps/LKL/LKL]


build.py...
: error F002: Failed to build module
/home/robin/repo/out/target/arm/uefiapp_LKL/EFIDroidUEFIApps/LKL/LKL.inf [ARM, GCC5, DEBUG]

- Failed -
Build end time: 12:11:25, Jun.28 2017
Build total time: 00:00:52

out/build.mk:960: recipe for target 'arm_uefiapp_LKL' failed
make[1]: *** [arm_uefiapp_LKL] Error 1
make[1]: *** Waiting for unfinished jobs....
configure.ac:9: installing './compile'
configure.ac:4: installing './config.guess'
configure.ac:4: installing './config.sub'
configure.ac:5: installing './install-sh'
configure.ac:5: installing './missing'
example/Makefile.am: installing './depcomp'
make[1]: Leaving directory '/home/robin/repo'

#### make failed to build some targets (08:19 (mm:ss)) ####

build/core/main.mk:38: recipe for target 'uefi' failed
make: *** [uefi] Error 2

**Comment by M1cha** [comment]
when you compile using multiple jobs, the end of the log is useless 99% of the time.
So you either have to post the full log or compile using -j1.

**Comment by AnierinBliss** [comment]
Yeah I tried compiling using -j4 at first then -j2 so I will try -j1. Sorry for all the comments and asking for help I'm a little new to all this so I appreciate the help man

_Sent from my Nextbit Robin using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by M1cha** [comment]
thx for asking instead of just giving up :D

**Comment by AnierinBliss** [comment]
it seems to be roughly the same error when compiling using -j1

In file included from /home/robin/repo/out/target/arm/uefiapp_LKL/EFIDroidUEFIApps/LKL/LKL.h:55:0,
from /home/robin/repo/out/target/arm/uefiapp_LKL/EFIDroidUEFIApps/LKL/ComponentName.c:22:
/home/robin/repo/out/target/arm/uefiapp_LKL/EFIDroidLKL/include/lkl_host.h:25:8: error: redefinition of 'struct iovec'
struct iovec {
^~~~~
In file included from /home/robin/repo/uefi/edk2/StdLib/Include/sys/socket.h:100:0,
from /home/robin/repo/out/target/arm/uefiapp_LKL/EFIDroidLKL/include/lkl/linux/if.h:27,
from /home/robin/repo/out/target/arm/uefiapp_LKL/EFIDroidLKL/include/lkl/asm/syscalls.h:108,
from /home/robin/repo/out/target/arm/uefiapp_LKL/EFIDroidLKL/include/lkl.h:13,
from /home/robin/repo/out/target/arm/uefiapp_LKL/EFIDroidUEFIApps/LKL/LKL.h:54,
from /home/robin/repo/out/target/arm/uefiapp_LKL/EFIDroidUEFIApps/LKL/ComponentName.c:22:
/home/robin/repo/uefi/edk2/StdLib/Include/sys/uio.h:57:8: note: originally defined here
struct iovec {
^~~~~
make[2]: *** [/home/robin/repo/out/target/arm/uefiapp_LKL/Build/EFIDroidUEFIApps/DEBUG_GCC5/ARM/EFIDroidUEFIApps/LKL/LKL/OUTPUT/ComponentName.obj] Error 1
GNUmakefile:2172: recipe for target '/home/robin/repo/out/target/arm/uefiapp_LKL/Build/EFIDroidUEFIApps/DEBUG_GCC5/ARM/EFIDroidUEFIApps/LKL/LKL/OUTPUT/ComponentName.obj' failed
make[2]: Leaving directory '/home/robin/repo/out/target/arm/uefiapp_LKL/Build/EFIDroidUEFIApps/DEBUG_GCC5/ARM/EFIDroidUEFIApps/LKL/LKL'


build.py...
: error 7000: Failed to execute command
make tbuild [/home/robin/repo/out/target/arm/uefiapp_LKL/Build/EFIDroidUEFIApps/DEBUG_GCC5/ARM/EFIDroidUEFIApps/LKL/LKL]


build.py...
: error F002: Failed to build module
/home/robin/repo/out/target/arm/uefiapp_LKL/EFIDroidUEFIApps/LKL/LKL.inf [ARM, GCC5, DEBUG]

- Failed -
Build end time: 17:23:33, Jun.28 2017
Build total time: 00:00:07

out/build.mk:960: recipe for target 'arm_uefiapp_LKL' failed
make[1]: *** [arm_uefiapp_LKL] Error 1
make[1]: Leaving directory '/home/robin/repo'

#### make failed to build some targets (52 seconds) ####

build/core/main.mk:38: recipe for target 'uefi' failed
make: *** [uefi] Error 2

**Comment by M1cha** [comment]
try to downgrade uefi/lkl to a063e1631db5e2b9b04f184c5e6d185c1cd645cb

**Comment by AnierinBliss** [comment]
how would I do so?

**Comment by M1cha** [comment]
uefi and lk do always run in 32bit compat mode.
`cd uefi/lkl`
`git checkout a063e1631db5e2b9b04f184c5e6d185c1cd645cb`

**Comment by AnierinBliss** [comment]
I've gotten lk to boot and display seems to be working decent. finalize_device worked with running the envsetup.sh with sudo -s

**Comment by AnierinBliss** [comment]
I managed to to port uefi but its not listing any installed os although it does for selecting fastboot os.
I can also reboot into twrp from holding power button down on reboot and selecting recovery
@AnierinBliss

**Comment by M1cha** [comment]
that's totally normal because your ESP hasn't been set up yet.
just fastboot boot twrp from within uefi-fastboot, then go back to uefi and everything should appear.

**Comment by AnierinBliss** [comment]
I got them to list but it's saying no DTB found for the board <251 8 0x10000>,
0x20009/0x2000a/0x0/0x0

**Comment by AnierinBliss** [comment]
![img_20170630_154232_01](https://user-images.githubusercontent.com/29746164/27751549-dec8b836-5daa-11e7-90ca-a49586f16937.jpg)
![img_20170630_154238_01](https://user-images.githubusercontent.com/29746164/27751555-e28ba474-5daa-11e7-9db4-b326a90cb44b.jpg)

**Comment by M1cha** [comment]
add this to device/X/Y/lk_inc.mk:
`DEVICE_PREFER_ATAGS_HWID := 1`

**Comment by AnierinBliss** [comment]
Alright that did it! Now one last question before i Go through the checklist. How do i add roms to test and see if multiboot is working. Downloading the app from the play store gives an error upon launching about my device

**Comment by z3ntu** [comment]
https://github.com/efidroid/projectmanagement/wiki/%5BEFIDroid%5D-Porting-a-new-device#local-ota-server-for-using-efidroid-manager-with-a-new-device

**Comment by AnierinBliss** [comment]
root@buildbox-ether:~/efi# start_local_otaserver PORT
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 600, in test
    port = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'PORT'
root@buildbox-ether:~/efi#

**Comment by AnierinBliss** [comment]
I cant seem to get my device to inteact with the ota server correctly. When i open the app it hits me with the devices.json list and error saying it cant load device info and in my pc terminal i get hit wtih

 root@buildbox-ether:~/efi# start_local_otaserver 80
Serving HTTP on 0.0.0.0 port 80 ...
10.0.0.40 - - [30/Jun/2017 21:21:02] "GET /ota/master/devices.json HTTP/1.1" 200

**Comment by AnierinBliss** [comment]
![screenshot_20170630-223018](https://user-images.githubusercontent.com/29746164/27758522-de4e83a2-5de3-11e7-9f4d-3cdb733daf3b.png)
![screenshot_20170630-223048](https://user-images.githubusercontent.com/29746164/27758523-def62c4c-5de3-11e7-8f69-1403cccf424e.png)

**Comment by AnierinBliss** [comment]
I can't seem to get the ota server set up correctly. 

keep getting hit with:
root@buildbox-ether:~/efi# start_local_otaserver 39804
Serving HTTP on 0.0.0.0 port 39804 ...
10.0.0.40 - - [30/Jun/2017 23:15:05] "GET /ota/master/devices.json HTTP/1.1" 200 -


@M1cha

**Comment by M1cha** [comment]
@AnierinBliss Sry that I didn't mention that earlier, but keep in mind that I currently don't add any new official devices in favor of the big rewrite.

You can still use it with a local or unofficial OTA server though.

**Comment by M1cha** [comment]
about your ota server issue:  it sounds like you forgot to add your device to devices.json

**Comment by AnierinBliss** [comment]
@M1cha I already did and its the same device name that the app requested even before trying to port this. as well as the same vendor_device (nextbit_ether) which is the same way my directories are set up for the device in efi.. Have any ideas?
{
    "fairphone/fp2": "fairphone/fp2",

    "motorola/condor_umts": "motorola/condor",
    "motorola/condor_umtsds": "motorola/condor",
    "motorola/peregrine": "motorola/peregrine",
    "motorola/peregrine_cdma": "motorola/peregrine",
    "motorola/peregrine_umts": "motorola/peregrine",
    "motorola/thea": "motorola/thea",

    "nokia/ara": "nokia/ara",

    "oneplus/a0001": "oneplus/bacon",
    "oneplus/bacon": "oneplus/bacon",

    "pantech/ef63": "pantech/ef63",
    "pantech/ef63s": "pantech/ef63",
    "pantech/ef63k": "pantech/ef63",
    "pantech/ef63l": "pantech/ef63",

    "samsung/trlte": "samsung/trlte",
    "samsung/trltecan": "samsung/trlte",
    "samsung/trltedt": "samsung/trlte",
    "samsung/trlteduoszh": "samsung/trlte",
    "samsung/trltespr": "samsung/trlte",
    "samsung/trltetmo": "samsung/trlte",
    "samsung/trlteusc": "samsung/trlte",
    "samsung/trltevzw": "samsung/trlte",
    "samsung/trltexx": "samsung/trlte",

    "xiaomi/aries": "xiaomi/aries",
    "xiaomi/cancro": "xiaomi/cancro",
    "xiaomi/libra": "xiaomi/libra",

    "nextbit/ether": "nextbit/ether",
    "nextbit/robin": "nextbit/ether",

**Comment by M1cha** [comment]
the last entry in a json array isn't allowed to have a trailing ','.

**Comment by AnierinBliss** [comment]
So  remove the last comma and then re make otapackage?

**Comment by M1cha** [comment]
yes but you don't need to recompile after editing ota server files.

**Comment by AnierinBliss** [comment]
@M1cha 
It's still just saying 10.0.0.40 - - [01/Jul/2017 01:52:49] "GET /ota/master/devices.json HTTP/1.1" 200 every time i open the manager app on my terminal and my device still list's devices.json. This is my info.json
[
  {
    "file": "http://10.0.0.217:80/builds/nextbit/ether/otapackage-20170701-nextbit_ether.zip",
    "timestamp": 0
  }
]

**Comment by M1cha** [comment]
your info.json doesn't matter because if I understood you correctly, it never gets fetched by the app.
So your device id is probably different from what you think.

At this point it would make sense to compile the appy ourself in debug mode and set a break point if that's something you are experienced with.

**Comment by AnierinBliss** [comment]
I honestly have no clue how I would do that man.. Oh well maybe I can try and figure out what the actually device ID it's calling for tomorrow.. before all this, and when downloading the efi manager app it said device not found for nextbit/ether so I don't understand how it wouldn't be right

**Comment by M1cha** [comment]
you can assume that nextbit/ether is correct then.
Which means that there's something else failing. Unfortunately I have no idea what that could be.
Maybe a logcat would give us some ideas.

**Comment by AnierinBliss** [comment]
@M1cha Logcat while trying to open the app or from lk/uefi

**Comment by M1cha** [comment]
while working with the app. lk/uefi don't have logcat(or adb) :)

**Comment by AnierinBliss** [comment]
{
    "nextbit/ether": "nextbit/ether"
}

fixing (}) this made the app say cant load device info index 1 size 1.. What does that mean?

**Comment by feherneoh** [comment]
first index is 0, not 1, so there is no "index 1" if the size is 1

**Comment by AnierinBliss** [comment]
so i got the app to load and what not but when i go to install it stops at 30 percent and says handshake failed

**Comment by M1cha** [comment]
does the server log mention anything about this error?
"handshake failed" sounds like you accidentally used https instead of http somewhere.
The local server doesn't support any kind of encrypted connections.

**Comment by AnierinBliss** [comment]
lol whoops that did it but now it cant find the esp partition

**Comment by M1cha** [comment]
your fstab.multiboot file is probably wrong.

**Comment by AnierinBliss** [comment]
How would I gather the necessary info to make it work correctly? sorry

**Comment by M1cha** [comment]
@AnierinBliss that's the problem. the "default" one is just an example.
If the paths and partitions aren't correct it won't work-

**Comment by AnierinBliss** [comment]
what can I do to figure out the correct ones?

**Comment by M1cha** [comment]
well check if these paths exist on Android. If not, use the correct ones(e.g. from your ROM's fstab).
Important: don't copy the whole fstab of your rom, while the name is similar, they meanings are different.

**Comment by M1cha** [comment]
https://github.com/efidroid/projectmanagement/wiki/%5BReference%5D-fstab.multiboot

**Comment by AnierinBliss** [comment]
this is what is in my fstab on my device... I honestly don't know where to put what..
# The filesystem that contains the filesystem checker binary (typically /system) cannot
# specify MF_CHECK, and must come before any filesystems that do specify MF_CHECK

#TODO: Add 'check' as fs_mgr_flags with data partition.
# Currently we dont have e2fsck compiled. So fs check would failed.

#<src>                                  <mnt_point>        <type>  <mnt_flags and options>                         <fs_mgr_flags>
/dev/block/bootdevice/by-name/system    /system            ext4    ro,barrier=1                                    wait
/dev/block/bootdevice/by-name/userdata  /data              f2fs    nosuid,nodev,noatime,nodiratime,inline_xattr,data_flush    wait,check,encryptable=footer,formattable,length=-16384
/dev/block/bootdevice/by-name/userdata  /data              ext4    nosuid,nodev,noatime,nodiratime,barrier=1,noauto_da_alloc  wait,check,encryptable=footer,formattable,length=-16384
/dev/block/bootdevice/by-name/cache     /cache             f2fs    nosuid,nodev,noatime,nodiratime,inline_xattr,flush_merge,data_flush    wait,check,formattable
/dev/block/bootdevice/by-name/cache     /cache             ext4    nosuid,nodev,noatime,nodiratime,barrier=1       wait,check,formattable
/dev/block/bootdevice/by-name/box       /BBSYS             ext4    nosuid,nodev,noatime,nodiratime,barrier=1       wait,check,formattable
/dev/block/bootdevice/by-name/boot      /boot              emmc    defaults                                        defaults
/dev/block/bootdevice/by-name/recovery  /recovery          emmc    defaults                                        defaults
/dev/block/bootdevice/by-name/misc      /misc              emmc    defaults                                        defaults
/dev/block/bootdevice/by-name/frp       /frp               emmc    defaults                                        defaults

/devices/soc.0/f9a55000.ehci/usb1       /storage/uicc0     vfat    nosuid,nodev                                    voldmanaged=uicc0:a

**Comment by M1cha** [comment]
well as you can see the paths are just different. So compare and correct them.

**Comment by AnierinBliss** [comment]
/dev/block/bootdevice/by-name/system       /system         ext4    defaults multiboot
/dev/block/bootdevice/by-name/cache         /cache          f2fs    defaults multiboot
Updated it to read this. Correct?

/dev/block/bootdevice/by-name/userdata     /data           ext4    defaults multiboot,esp=datamedia
/dev/block/bootdevice/by-name/boot         /boot           emmc    defaults multiboot,uefi,nvvars
/dev/block/bootdevice/by-name/recovery     /recovery       emmc    defaults uefi
/dev/block/platform/msm_sdcc.1/by-name/modem        /firmware       emmc    defaults

**Comment by M1cha** [comment]
https://github.com/efidroid/projectmanagement/wiki/%5BReference%5D-fstab.multiboot#filesystem

**Comment by AnierinBliss** [comment]
I used that guide and it still cant find esp partition. I used the above fstab.multiboot i made (changing ext4/f2s to auto)
