### ISSUE TITLE
Error build uefi

### ISSUE THREAD

**Issue by zhenyolka** [efidroid/projectmanagement#116]
Hello!
I build uefi variant on Windows WSL (ubuntu on windows) and see error.
Last log massages in file.
Sorry for my English
[log.txt](https://github.com/efidroid/projectmanagement/files/1133583/error_build_uefi_variant.txt)

**Comment by M1cha** [comment]
you have to downgrade uefi/lkl to a063e1631db5e2b9b04f184c5e6d185c1cd645cb

`cd uefi/lkl`
`git checkout a063e1631db5e2b9b04f184c5e6d185c1cd645cb`

**Comment by zhenyolka** [comment]
Thank you! All succesfull compile and boot!
