### ISSUE TITLE
Not support touchscreen and rotate screen

### ISSUE THREAD

**Issue by zhenyolka** [efidroid/projectmanagement#117]
On first start I see "not support touch screen in this bootloader" how fix it.
And screen rotate on 180 degrees. And boot loop cyanogenmod.
I port it to lg l65 (msm8610).

**Comment by M1cha** [comment]
Touchscreen input isn't supported by EFIDroid in general.
Neither is screen rotation.

Touchscreen support may be added someday in the future, but screen rotation is very unlikely since sensor drivers usually run on a coprocessor which needs to be initialized via trustedzone.

**Comment by z3ntu** [comment]
I think he means that his display is mounted upside down (see eg OnePlus 5 news) so everything should be displayed upside-down.

**Comment by M1cha** [comment]
@z3ntu thx for clearing that up. I'll add software rotation to my TODO list for UI2.
