### ISSUE TITLE
Port for lg l65

### ISSUE THREAD

**Issue by zhenyolka** [efidroid/projectmanagement#118]
I finish port EFIDroid to lg l65.
All work, I try, but screen in my phone mount not normally, on 180 degress and image on screen is rotated.
I upload 
[otapackage-20170710-lge_l65.zip](https://github.com/efidroid/projectmanagement/files/1136465/otapackage-20170710-lge_l65.zip)
Please add this port to you official app.

**Comment by M1cha** [comment]
I will not accept any device ports before the big rewrite is done because every device has to be ported from scratch afterwards anyway.

**Comment by M1cha** [comment]
Besides, I don't accept binaries. Everything has to be opensource.
