### ISSUE TITLE
How boot grub?

### ISSUE THREAD

**Issue by zhenyolka** [efidroid/projectmanagement#119]
I read that the EFIDroid can run GRUB. How it can be done. It is connected via Google translator.

**Comment by M1cha** [comment]
```
make uefiapp_grub
fastboot boot out/device/X/Y/uefiapp_grub/grubboot.img
```

**Comment by zhenyolka** [comment]
Error
[log.txt](https://github.com/efidroid/projectmanagement/files/1136601/log.txt)

**Comment by zhenyolka** [comment]
What do?
