### ISSUE TITLE
How to remove efidroid

### ISSUE THREAD

**Issue by E4rx** [efidroid/projectmanagement#123]
Hi, i installed efidroid on my device but i dont know how to remove it. How do i remeve it?

**Comment by M1cha** [comment]
just hit the uninstall button in the android app(the trash bin icon)

**Comment by E4rx** [comment]
And where is it?
Because i dont find it anywhere

**Comment by z3ntu** [comment]
![image](https://user-images.githubusercontent.com/3768500/29069897-290ede92-7c3d-11e7-91c4-95f9c5eca194.png)

**Comment by E4rx** [comment]
Thx. You helped me a lot

**Comment by feherneoh** [comment]
@M1cha Can you close this? Seems to be solved
