### ISSUE TITLE
EFIDroid Manager: unoffical ports specified in wiki doesnt work

### ISSUE THREAD

**Issue by HardSer** [efidroid/projectmanagement#124]
Hello!
In project-management wiki i saw that Xiaomi Redmi Note 3 Pro (kenzo) is in Unoffical section.
Installed EFIDroid Manager, it wrote "Unable to load device info for xiaomi/kenzo".
How to install EFIDroid on this device through?

**Comment by feherneoh** [comment]
Look for the unofficial port on the web, if you can find it, most probably there will be an installation tutorial too

**Comment by HardSer** [comment]
Found "EFIDroid will be for Kenzo soon" only, dated 12 November 2016.

**Comment by HardSer** [comment]
Decided to build myself.
