### ISSUE TITLE
Can EFiDroid take advantage of Qualcomm's closed source UEFI bootloaders?

### ISSUE THREAD

**Issue by zhuowei** [efidroid/projectmanagement#126]
On Snapdragon 820 and above, Qualcomm's closed source proprietary bootloader, XBL, is based on edk2., and on 835, abl is now a [UEFI application](https://source.codeaurora.org/quic/la/abl/tianocore/edk2/tree/QcomModulePkg/Application/LinuxLoader/LinuxLoader.c?h=LA.UM.5.7.r1-10900-8x98.0) instead of LK. Could EFIDroid use those somehow?

**Comment by M1cha** [comment]
I don't think so because qcom doesn't allow running efi files.
Ofc we could try to sideload a closed source uefi and add our own files to the FV but I think that people prefer an open source solution. (And I don't wanna risk DMCA takedowns)

**Comment by zhuowei** [comment]
@M1cha so what is the plan for supporting Snapdragon 835 devices, then? I can't find an lk with support.

**Comment by M1cha** [comment]
well we can try to use lk's drivers and enhance them with the linux-drivers for 835.
We're not using LK anymore anyway.

**Comment by zhuowei** [comment]
@M1cha thank you so much for your response!
