### ISSUE TITLE
Cant compile edk2

### ISSUE THREAD

**Issue by GITInvoker** [efidroid/projectmanagement#130]
1. fails so much with xiaomi/aries device -> log below
2. by the way efidroid fails on every device when i try to compile with make edk2! says EFIDROID_PLATFORM etc. wasnt defined ! i know because there is no edk2 config file for other device then aries! this whole project is totally useless for me!

**Comment by GITInvoker** [comment]
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c: In function ‘LibQcomPlatformUartDmGpioConfig’:
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:36:12: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(MSM_BOOT_UART_SWITCH_GPIO_MITWOA, 0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_16MA, GPIO_ENABLE);
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:36:68: error: ‘GPIO_OUTPUT’ undeclared (first use in this function); did you mean ‘GPIO_PULL’?
gGpioTlmm->gpio_tlmm_config(MSM_BOOT_UART_SWITCH_GPIO_MITWOA, 0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_16MA, GPIO_ENABLE);
^~~~~~~~~~~
GPIO_PULL
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:36:68: note: each undeclared identifier is reported only once for each function it appears in
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:36:81: error: ‘GPIO_NO_PULL’ undeclared (first use in this function); did you mean ‘GPIO_PULL’?
gGpioTlmm->gpio_tlmm_config(MSM_BOOT_UART_SWITCH_GPIO_MITWOA, 0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_16MA, GPIO_ENABLE);
^~~~~~~~~~~~
GPIO_PULL
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:36:95: error: ‘GPIO_16MA’ undeclared (first use in this function); did you mean ‘GPIO_PULL’?
gGpioTlmm->gpio_tlmm_config(MSM_BOOT_UART_SWITCH_GPIO_MITWOA, 0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_16MA, GPIO_ENABLE);
^~~~~~~~~
GPIO_PULL
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:36:106: error: ‘GPIO_ENABLE’ undeclared (first use in this function); did you mean ‘GPIO_PULL’?
gGpioTlmm->gpio_tlmm_config(MSM_BOOT_UART_SWITCH_GPIO_MITWOA, 0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_16MA, GPIO_ENABLE);
^~~~~~~~~~~
GPIO_PULL
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:37:12: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_set’
gGpioTlmm->gpio_set(MSM_BOOT_UART_SWITCH_GPIO_MITWOA, 2);
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:40:12: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(MSM_BOOT_UART_SWITCH_GPIO_MITWO, 0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_16MA, GPIO_ENABLE);
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:41:12: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_set’
gGpioTlmm->gpio_set(MSM_BOOT_UART_SWITCH_GPIO_MITWO, 2);
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:50:13: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(23, 2, GPIO_INPUT, GPIO_NO_PULL,
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:50:39: error: ‘GPIO_INPUT’ undeclared (first use in this function); did you mean ‘GPIO_OUTPUT’?
gGpioTlmm->gpio_tlmm_config(23, 2, GPIO_INPUT, GPIO_NO_PULL,
^~~~~~~~~~
GPIO_OUTPUT
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:51:9: error: ‘GPIO_8MA’ undeclared (first use in this function); did you mean ‘GPIO_16MA’?
GPIO_8MA, GPIO_DISABLE);
^~~~~~~~
GPIO_16MA
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:51:19: error: ‘GPIO_DISABLE’ undeclared (first use in this function); did you mean ‘GPIO_ENABLE’?
GPIO_8MA, GPIO_DISABLE);
^~~~~~~~~~~~
GPIO_ENABLE
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:53:13: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(22, 2, GPIO_OUTPUT, GPIO_NO_PULL,
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:69:13: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(19, 1, GPIO_INPUT, GPIO_NO_PULL,
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:72:13: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(18, 1, GPIO_OUTPUT, GPIO_NO_PULL,
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:79:13: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(83, 1, GPIO_INPUT, GPIO_NO_PULL,
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:82:13: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(82, 2, GPIO_OUTPUT, GPIO_NO_PULL,
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:96:13: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(15, 1, GPIO_INPUT, GPIO_NO_PULL,
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:99:13: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(14, 1, GPIO_OUTPUT, GPIO_NO_PULL,
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:105:13: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(23, 1, GPIO_INPUT, GPIO_NO_PULL,
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:108:13: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
GNUmakefile:379: recipe for target '/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/Build/EFIDroid-ARM/DEBUG_GCC5/ARM/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib/OUTPUT/QcomPlatformUartDmLib.obj' failed
gGpioTlmm->gpio_tlmm_config(22, 1, GPIO_OUTPUT, GPIO_NO_PULL,
make[2]: Leaving directory '/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/Build/EFIDroid-ARM/DEBUG_GCC5/ARM/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib'
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:114:13: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(35, 1, GPIO_INPUT, GPIO_NO_PULL,
^~
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.c:117:13: error: ‘QCOM_GPIO_TLMM_PROTOCOL {aka struct _QCOM_GPIO_TLMM_PROTOCOL}’ has no member named ‘gpio_tlmm_config’
gGpioTlmm->gpio_tlmm_config(34, 1, GPIO_OUTPUT, GPIO_NO_PULL,
^~
make[2]: *** [/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/Build/EFIDroid-ARM/DEBUG_GCC5/ARM/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib/OUTPUT/QcomPlatformUartDmLib.obj] Error 1


build.py...
: error 7000: Failed to execute command
make tbuild [/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/Build/EFIDroid-ARM/DEBUG_GCC5/ARM/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib]


build.py...
: error F002: Failed to build module
/home/invoker/EFIDroid/out/device/xiaomi/aries/edk2/EFIDroidDevicePkg/Library/QcomPlatformUartDmLib/QcomPlatformUartDmLib.inf [ARM, GCC5, DEBUG]

- Failed -
Build end time: 13:26:11, Jan.22 2018
Build total time: 00:02:07

**Comment by feherneoh** [comment]
something seems to be messed up in your source tree

**Comment by M1cha** [comment]
I forgot to push some changes - I've done that now :)

**Comment by M1cha** [comment]
about 1) that sounbds like you're trying to compile edk2 without efidroids build system.

**Comment by GITInvoker** [comment]
Thanks for changes what fixed and I know that two device is only supported for EFI sompile but I couldnt even compile for those... I check out now what happen hope it works :)

**Comment by GITInvoker** [comment]
I want to port an own device for EFI on this
