### ISSUE TITLE
Building efidroid fails

### ISSUE THREAD

**Issue by pinoaffe** [efidroid/projectmanagement#132]
When I tried to port efidroid to another device, i got the error message `Error: [Errno 2] No such file or directory: 'build/templates/lk_inc.template.mk'` upon running the create_device script
I tried to look for the file in other places, but couldn't find it in any of the repos.
What might be the cause?
Furthermore, it seems like the documentation is hopelessly lacking - will this change, or is the project dead?

**Comment by M1cha** [comment]
This will change, because as the top of the porting guide says, "This information is outdated because of the REWRITE.".

Porting the new code will be very different (we don't even use LK anymore).

**Comment by feherneoh** [comment]
> > This will change, because as the top of the porting guide says, "This information is outdated because of the REWRITE.".
> > Porting the new code will be very different (we don't even use LK anymore).
> 
> I have got the same error
> please give us a version number which we can build as old ways via "git checkout V...."

I'm pretty sure that you have noticed that this project uses repo, meaning you won't ever have a single git commit hash you can use. Go check the commit dates, and write a manifest for yourself. Everyone who needs the old (practically useless) tree does that.

**Comment by feherneoh** [comment]
64bit devices never worked correctly with the old sources, and there were problems with things like GApps too
