### ISSUE TITLE
Bug on OnePlus One makes this software useless

### ISSUE THREAD

**Issue by aksrocks54** [efidroid/projectmanagement#133]
Bug on the OPO (bacon). After installing EFIDroid, irrespective of the rom you flash if you try to flash gapps the system reboots and gives the message "Previous Boot Failed. Cant allocate child memory -9" or the error 139.
This happens on all primary as well as secondary roms.
If you uninstall EFIDroid, then flashing gapps is successful without any errors. This makes the app completely useless.
It seems like a small error to correct, can someone please look into it? Otherwise such a powerful piece of software.

**Comment by feherneoh** [comment]
Please read the other reported issues (closed ones too)
This problem got reported multiple times, is not that easy to fix, and also there will be no fixes to the old codebase, as a complete rewrite is currently in progress

Expect it to work when the new base is released, that will fix most of the known problems
