### ISSUE TITLE
EFIDROID_CHIPVENDOR not defined

### ISSUE THREAD

**Issue by cobalt9** [efidroid/projectmanagement#134]
I am getting this error
efidroid/uefi/edk2packages/EFIDroidPkg/EFIDroidPkg.dsc(285): error 3000: EFIDROID_CHIPVENDOR not defined
It doesn't go into Qcom folder.
I have tried to fix it but no luck so far.

I was trying to Moto/Condor to test.

**Comment by M1cha** [comment]
first off: you're compiling for the new code base: I'll come no further than to the edk2 shell.

Untested, but this is the code I've used last time:
/media/Data/repositories/git/efidroid2/device/motorola/condor/device-motorola-condor.tar.xz

**Comment by cobalt9** [comment]
Are you working on a whole new project or changing things in this existing project as I checked you mentioned somewhere that you are dumping lk in new builds.

**Comment by M1cha** [comment]
same project, same repos, different code :)
I didn't feel the need to keep the old code compilable since it had major bugs which would not be fixed in there anyway.

**Comment by GoliathLabs** [comment]
So are you rewriting the project or what? Looking forward to see some new stuff xD

**Comment by M1cha** [comment]
yes I am. To correct some technical mistakes and hopefully improve the multiboot situation.

**Comment by GoliathLabs** [comment]
And when can we expect a new release? :p

**Comment by M1cha** [comment]
I wish I knew :P

**Comment by M1cha** [comment]
it's never gonna happen:
https://github.com/efidroid/projectmanagement#-this-project-has-been-discontinued-more-info-
