### ISSUE TITLE
How to port efidroid to new devices?

### ISSUE THREAD

**Issue by nkrapivin** [efidroid/projectmanagement#135]
codename: xiaomi/santoni
description: Redmi 4X
density: 320
chipset: msm8937 (arm64)

Clean untouched boot.img from Global Developer 8.5.10
https://transfer.sh/XCbMA/boot.img

**Comment by feherneoh** [comment]
EFIDroid is in an incomplete state right now, but if you are willing to work on chip support, I can provide you with help about doing it

**Comment by nkrapivin** [comment]
And I also have another qcom device (actually my friend's phone, he dislikes DualBootPatcher)
codename: micromax/Q415
description: Pace 4G
# full name of this device is Micromax Canvas Pace 4G, but model of this device is Q415
density: idk lol, maybe 240
chipset: msm8909 (**32bit**, no 64bit kernel support.)

Clean untouched boot.img leaked from micromax full pc 5.1.1 firmware (this phone also have 6.0 firm)
https://transfer.sh/6G47I/boot_sw3.1.img

**Comment by feherneoh** [comment]
You can contact me on telegram (same username) or in the EFIDroid Slack to get help on porting

**Comment by thchi12** [comment]
hmmm...Do you have any ideas? I wamt to port to my msm8926 device...But the page on wiki says it's outdated and I don't know what to do now.

**Comment by feherneoh** [comment]
As the old implementation had some hard-to-fix functionality-breaking bugs on new devices, a full rewrite was started, and it's not in an usable state yet

**Comment by thchi12** [comment]
Then can I get an earlier working build environment?

**Comment by M1cha** [comment]
here you go:
https://github.com/efidroid/manifest/tree/master-legacy
