### ISSUE TITLE
Help me port for kenzo

### ISSUE THREAD

**Issue by TheDeaX-Lab** [efidroid/projectmanagement#136]
I have error on makefile:

[deax@TheDeaX efibuild]$ make -j4 lk
Looking for dependencies
Buildtype: DEBUG
Device: xiaomi/kenzo
Architectures: arm
Configuring for host, target, device
make[1]: вход в каталог «/home/deax/efibuild»
make[1]: *** Нет правила для сборки цели «lk».  exit
make[1]: выход из каталога «/home/deax/efibuild»

#### make failed to build some targets  ####

make: *** [build/core/main.mk:42: lk] error 2

**Comment by M1cha** [comment]
you nee to use the old code:
https://github.com/efidroid/manifest/tree/master-legacy
