### ISSUE TITLE
New porting instructions?

### ISSUE THREAD

**Issue by ghost** [efidroid/projectmanagement#139]
Apparently there were changes, and i'm curious. I want to port this to my device.

**Comment by feherneoh** [comment]
Porting instructions will be updated when it's ready to be ported

**Comment by steamp0rt** [comment]
OK. Thanks.

**Comment by luka177** [comment]
Is project dead?
if not can i help, i have msm8937 device and uart on it

**Comment by 1231133** [comment]
I have Speadtrum 7731 g device.

**Comment by M1cha** [comment]
I stopped working on it:
https://github.com/efidroid/projectmanagement#-this-project-has-been-discontinued-more-info-
