### ISSUE TITLE
Can't uninstall/open Efidroid because no root access

### ISSUE THREAD

**Issue by matwalk86** [efidroid/projectmanagement#141]
Hi, 
I was these last months on lineage 15.1 with twrp. 

Then yesterday, I decided to install efidroid and /e/ (or eelo) rom on my fairphone 2. My goal would have been having dual boot /e/ and lineage os. 
The problem is that I forgot to install before addon supersu on /e/ and I have no root access now on it. On /e/ I cant do factory reset. 

On efidroid, Twrp doesn't display. So I'm stuck on /e/ without the possibility to go back on my lineage. Does anyone could help me? Thanks in advance.

**Comment by z3ntu** [comment]
Just flash TWRP again.

**Comment by matwalk86** [comment]
Thank you! I flashed it succesfully! :)

**Comment by MLXProjects** [comment]
Problem solved and issue not closed? Really?
