### ISSUE TITLE
build error :  'build/templates/lk_inc.template.mk'

### ISSUE THREAD

**Issue by S-8506** [efidroid/projectmanagement#146]
s-8506@s8506-X556UR:~/Desktop/EFIdroid$ create_device  path/to/boot.img
Device name (vendor/codename): zuk/z2_plus
Device Description (i.e. Moto E): zuk z2_plus
LCD Density: 420
Available targets:
                 msm8996                 msm7627a                  apq8084                  msm8226
                 msm8610                  msm8660                  msm8960                  msm8974
                 msm8994                  msm8909                  msm8916                  msm8952
LK Target: msm8996
Error: [Errno 2] No such file or directory: 'build/templates/lk_inc.template.mk'
Traceback (most recent call last):
  File "/home/s-8506/Desktop/EFIdroid/build/tools/create_device", line 232, in <module>
    runmain(main)
  File "/home/s-8506/Desktop/EFIdroid/build/tools/../core/utils.py", line 91, in runmain
    sys.exit(main(sys.argv[1:]))
  File "/home/s-8506/Desktop/EFIdroid/build/tools/create_device", line 228, in main
    copyfile('build/templates/lk_inc.template.mk', devicedir+'/lk_inc.mk')
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'build/templates/lk_inc.template.mk'

**Comment by luka177** [comment]
try older commits

**Comment by M1cha** [comment]
you can use this branch now:
https://github.com/efidroid/manifest/tree/master-legacy
