### ISSUE TITLE
EFIDroidDevicePkg.dsc.inc Can fix this error?

### ISSUE THREAD

**Issue by soicry** [efidroid/projectmanagement#150]
Hello,

I'm trying to build EFIDroid using Sony's Castor Windy Config, but I'm getting this error and unable to proceed. I tried build another device but it is the same error. This error
EFIDroidDevicePkg/EFIDroidDevicePkg.dsc.inc is not found in packages path:, which should load EFIDroidDevicePkg from /home/hyundai/efidroid/uefi/edk2packages/EFIDroidPkg/EFIDroidPkg.dsc(285). It doesn't build because there's no folder and dsc.inc. I checked the Manifest and EFIDroid projects and this folder "EFIDroidDevicePkg" doesn't exist. How can I solve this problem?
sorry my english.
![abc](https://user-images.githubusercontent.com/50505049/67373146-11087580-f5ba-11e9-945b-10e619a8cbcf.PNG)

Thank you in advance.

**Comment by feherneoh** [comment]
EFIDroidDevicePkg is your device folder, so device/sony/castor-windy in your case
Check the xiaomi/aries branch of https://github.com/efidroid/device for an example

**Comment by soicry** [comment]
Thank you. and, can I ask another question?

**Comment by soicry** [comment]
Thank you very much if you can answer.

My other question is this. 
This is an error called can't open file. This error seems to be an error in drivers/kconfig: 213, but if open the drivers/kconfig file, line 213 does not exist.
Thank you very much.
![11](https://user-images.githubusercontent.com/50505049/67464501-627a3880-f67e-11e9-8281-dcd59af66aba.PNG)
![22](https://user-images.githubusercontent.com/50505049/67464505-63ab6580-f67e-11e9-9ec9-d45cb60c0606.PNG)

**Comment by feherneoh** [comment]
The EFIDroid build system does some symlinking and patching before building things, so it can add some files/lines build-time. You have to find the script that sets up lkl before building it, should be somewhere in the build repo

**Comment by soicry** [comment]
Thank you very much. :)
