### ISSUE TITLE
Error Porting Mi A2

### ISSUE THREAD

**Issue by XRedCubeX** [efidroid/projectmanagement#151]
Hi, I'm having trouble porting EFIDroid to Mi A2 and giving me various errors, I am attaching the text file in which everything is written in the terminal.
[errorfidroidmia2.txt](https://github.com/efidroid/projectmanagement/files/3798110/errorfidroidmia2.txt)

**Comment by feherneoh** [comment]
You made the same mistake as 99% of the issue-openers here.

You are trying to use the tutorials and scripts written for the old codebase to work with the new codebase.

There are NO working scripts and tutorials for the new codebase, and the platform you are trying to build for isn't supported at all in the new code.
The chipset you are working with is a 64-bit one, so you will probably not have luck with the old codebase either.
On another note, the multiboot part of the project was last updated somewhere around the N release, so even if you somehow manage to get it to build and boot up, don't expect O, P and Q ROMs to work with it. Same goes for A/B devices and possibly Treble ones.

**Comment by XRedCubeX** [comment]
In fact my device no longer has LK but does not have a guide on the new code?

**Comment by feherneoh** [comment]
> In fact my device no longer has LK but does not have a guide on the new code?

Oh, right, I didn't check what SoC sour device has, only what you picked in create_device
