### ISSUE TITLE
make[1]: *** No rule to make target 'lk'.  Stop.

### ISSUE THREAD

**Issue by sashapzzx** [efidroid/projectmanagement#158]
┌──(root💀DESKTOP-E6VC3O6)-[/home/kali/auefi]
└─# make -j lk
Looking for dependencies
Buildtype: DEBUG
Device: 3.4.0/ms013g
Architectures: arm
Configuring for host, target, device
make[1]: Entering directory '/home/kali/auefi'
make[1]: *** No rule to make target 'lk'.  Stop.
make[1]: Leaving directory '/home/kali/auefi'

#### make failed to build some targets  ####

make: *** [build/core/main.mk:42: lk] Error 2
┌──(root💀DESKTOP-E6VC3O6)-[/home/kali/auefi]
└─#

how to fix it?

**Comment by feherneoh** [comment]
By trying to build a target that actually exists on said revision

**Comment by sashapzzx** [comment]
but what target is exists

**Comment by sashapzzx** [comment]
i tryed make -j lk uefi

**Comment by M1cha** [comment]
you have to use the old LK code if you want to follow the old guide.
https://github.com/efidroid/manifest/tree/master-legacy
