### ISSUE TITLE
--defsym=PECOFF_HEADER_SIZE=0x220 -Wno-error

### ISSUE THREAD

**Issue by Oleksandr-Holiak** [efidroid/projectmanagement#160]
When make -j uefi
- Done -
Build end time: 22:08:11, Apr.11 2021
Build total time: 00:02:48

Installing: /home/kali/uefi/out/target/arm/uefiapp_EFIDroidUi/Build/EFIDroidUEFIApps/RELEASE_GCC5/ARM/EFIDroidUi.efi
make[1]: Leaving directory '/home/kali/uefi'

#### make failed to build some targets (05:25 (mm:ss)) ####

make: *** [build/core/main.mk:44: uefi] Error 2

I have long pause in --defsym=PECOFF_HEADER_SIZE=0x220 -Wno-error
I already make lk and it was successfully
I use this github.com/efidroid/manifest.git -b master-legacy

**Comment by Oleksandr-Holiak** [comment]
[full out.txt](https://github.com/efidroid/projectmanagement/files/6292602/full.out.txt)

**Comment by feherneoh** [comment]
Can you pipe the whole output (both stdout and stderr) into files? This file you sent only includes part of the output (your scrollback buffer might be too small for it), and the actual error is not shown here

**Comment by M1cha** [comment]
@sashapzzx please explain how you fixed it
