### ISSUE TITLE
EDK2_BASE is not set

### ISSUE THREAD

**Issue by Oleksandr-Holiak** [efidroid/projectmanagement#162]
when i do make -j uefi
[output.txt](https://github.com/efidroid/projectmanagement/files/6295336/output.txt)

Compiling arm_uefird_multiboot_init
Compiling uefird
3504 blocks
Compiling edk2
EDK2_BASE is not set
make[1]: [out/build.mk:545: edk2] Error 1
Compiling lkuefi_kernel_final
stat: missing operand
Try 'stat --help' for more information.
make[1]: [out/build.mk:1077: lkuefi_kernel_final] Error 1
Compiling uefi

What i do wrong again?

**Comment by M1cha** [comment]
you forgot the number of jobs after `-j`
correct command: `make -jX uefi` replace `X` with the number of jobs you want to compile with.

**Comment by Oleksandr-Holiak** [comment]
I have same problem with make -j5 uefi

**Comment by Oleksandr-Holiak** [comment]
help

**Comment by M1cha** [comment]
I don't know what the problem is but writing `help` after less then 24h on a weekend is not gonna speed things up.
try `V=1 VERBOSE=1 make -j1 uefi` and post the log of that.

**Comment by Oleksandr-Holiak** [comment]
[output.txt](https://github.com/efidroid/projectmanagement/files/6371803/output.txt)
Same problem

**Comment by M1cha** [comment]
well did you set EDK2_BASE in your devices config.ini?

**Comment by Oleksandr-Holiak** [comment]
no

**Comment by Oleksandr-Holiak** [comment]
But what should be in EDK2_BASE=?

**Comment by Oleksandr-Holiak** [comment]
[config.ini.txt](https://github.com/efidroid/projectmanagement/files/6372132/config.ini.txt)
This is my config.ini

**Comment by M1cha** [comment]
sounds like you forgot this step:
https://github.com/efidroid/projectmanagement/wiki/%5BEFIDroid%5D-Porting-a-new-device#update-loading-addresses

**Comment by Oleksandr-Holiak** [comment]
You say about this finalize_device device/3.4.0/ms013g? When i write it freezes. I wait more then hour but nothing never happened.

**Comment by M1cha** [comment]
well does lk_nouefi appear as a fastboot usb device? If not I can't help you because you have to make it boot
also keep in mind that the usb is different from your stock fastboot/adb ids so you might have to update udev rules

**Comment by Oleksandr-Holiak** [comment]
I use master-legacy branch

**Comment by Oleksandr-Holiak** [comment]
I already boot to nouefi and fastboot work
![nouefi](https://user-images.githubusercontent.com/62952395/115999156-62e8ec00-a5f3-11eb-8d9d-7a30b1287a73.jpg)

**Comment by M1cha** [comment]
then you have to figure out where and why finalize_device blocks forever

**Comment by Oleksandr-Holiak** [comment]
I already solved this problem. I used  windows 10 and download kali linux from microsoft store and I could not connect my device to fastboot. It only connect to windows but not to kali linux
