### ISSUE TITLE
why the project is discontinued

### ISSUE THREAD

**Issue by binbard** [efidroid/projectmanagement#165]
hello. I wanna know why this is no longer maintained. Does current project leads no success? Does it require contribution.

**Comment by M1cha** [comment]
this comment should explain it all:
https://github.com/efidroid/projectmanagement/issues/152#issuecomment-562019779

If you still have questions, feel free to ask :)

**Comment by harshitjawla** [comment]
thanks.
what I have learnt:
> the project needs some dedicated contributors
> it is probably not possible to be a universal multiboot system for all android devices 
first thanks for your nice work.
A year ago I have bricked my phone by flashing wrong image (giving no response least my pc), I was a complete newbie.
Since then, I got a great interest in android bootloading process, flashing protocols of different processors.
I will surely work upon the same after gathering more information and play with ported images, modified recovery.
Glad if you provide some suggetsoions/tips about getting started. 
thanks for giving much time for this poject.

**Comment by M1cha** [comment]
bricking hardware sucks but you learn a lot from that :smile: I hope it was just a softbrick though.
Well first you should probably dig into what kinda boot process current devices actually have.
AFAIK qcom devices are now using a closed-source edk2 fork which loads the LinuxLoader from the `abl`(Android Boot Loader) partition which is still opensource: https://source.codeaurora.org/quic/la/abl/tianocore/edk2/tree/QcomModulePkg?h=uefi.lnx.2.1.r22-rel

But of course some vendors(especially Samsung, motorola and sony) like to heavily modify their boot process and if you wanna know more about them you have to get familiar with reading aarch32 and aarch64 assembly and find ways to use the overpriced but awesome software `IDA Pro` and it's decompiler `hexrays`.
Reverse-Engeneering is specifically useful if the software is very close to the opensource(or leaked source) base(LK, edk2, ...) so you can see what the differences are.

But of course a lot of that is not necessary if you're not interested in writing your own bootloaders. And even if you are you could do it by writing your own drivers by looking at the linux kernel drivers of your device.

And a final hint about qualcom: Their git repos are a mess. They have a gazillion branches and tags and don't really like to have unified code-bases. So make sure you're looking at the right code.

**Comment by binbard** [comment]
Hi, thanks for your response.
Actually it is of mtk chipset (panasonic eluga z1)
I also assume it was softbricked, otherwise I would not able to revive it without messing with its hardware.
I was lucky that mtk phones can be flashed at their runtime (bootup) without going into any fastboot/adb/edl mode
though I have to disable secure boot everytime using other tool, before flashing rom at runtime.

Despite of successfully flashing whole stock ROM I still could not run full android. When I power it with usb, only then I am able to access fastboot|recovery|normal boot menu screen through vol+ button, lest there is no response. (when entering normal boot powered by android logo blinks for a second, then off, maybe android requires integrated battery for power). When I disconnect usb that screen too goes off (simply means my battery is dead and cannot be charged. - ofcourse tried charging for whole of days)

I'll get replace the battery and update you within a week. 
Last thing, Can I expect EFIdroid to be ported for my phone? I have read a bit of EFIdroid build system doc. and for me:
device/[VENDOR]/[CODENAME] = device/panasonic/cervino

**Comment by M1cha** [comment]
given that the old LK-based efidroid (probably) doesn't work at all with new Android versions and the pure edk2 based one isn't anywhere even close to working you have to ask yourself what you want to achieve.
If you just want UEFI you're probably best off compiling and porting mainline edk2 directly.
https://github.com/tianocore/edk2-platforms

**Comment by binbard** [comment]
Hi I have lk based bootloader (I got this as I have lk&lk2 files in my stock rom and not edk). I can try EFIdroid if I am not wrong :)

**Comment by M1cha** [comment]
do you have the sourcecode for your vendor LK? the lk-based efidroid implements a custom API and then runs a version of edk2 which uses that for most drivers which makes it quite platform independant.
That obiously means that you need a fully working, custom, opensource LK.

Also, I didn't know that mtk uses LK. is it based on qcom's fork or on mainline LK?

**Comment by binbard** [comment]
hi. I dont know. I tried searching for panasonic lk source and couldnt find any of the vendor's lk source code. Do any of the vendor really open source their lk? or the community pople do modify the original android lk to match vendors

Edit: I got to know that vendors have to opensource their kernels due to gpl licence. So I have mailed to panasonic.com as [some of the device kernel are opensourced](https://mobile.panasonic.com/in/support/opensourcearchives) but not of my device

**Comment by XRedCubeX** [comment]
@M1cha Mediatek uses a heavily customized version (from them) of Little Kernel and on github you can find some examples, in my repo you find something.

@utilmen The GPL speech only makes sense with the linux kernel, not the Little Kernel

**Comment by binbard** [comment]
Thankzz.  But I am in searcch of my device's linux kernel, but they have not oppensourced it for my device. 
Can I do something to get it (Is it easy to port linux kernel to any device)

**Comment by M1cha** [comment]
mediatek actively violates the GPL without facing any consequences thanks to their countries laws.
It looks like OEMs (like panasonic) are free to publish the sources anywhere but I don't know it they need a special contract for that or if they can just do it.
The tricky part is getting in contact with somebody at panasonic who both has technical knowledge and is allowed to make that decision. Support centers will never get you in contact with these people. Maybe you can find the right people on twitter, linkedin, github, ...?

**Comment by vizPilot** [comment]
Hello @M1cha i have to create a project similar to efidroid

**Comment by feherneoh** [comment]
> Hello @M1cha i have to create a project similar to efidroid

No, you don't have to.
You have to learn the basics before you go around annoying half the internet with your crap, spamming it everywhere, and bricking devices those don't even belong to you, because you just randomly copy-paste commands meant for other devices from who-knows-where. Stop this.

**Comment by vizPilot** [comment]
> > Hello @M1cha i have to create a project similar to efidroid
> 
> No, you don't have to. You have to learn the basics before you go around annoying half the internet with your crap, spamming it everywhere, and bricking devices those don't even belong to you, because you just randomly copy-paste commands meant for other devices from who-knows-where. Stop this.

I am not going to do that project
