### ISSUE TITLE
Is there new docs for the nolk version?

### ISSUE THREAD

**Issue by ghost** [efidroid/projectmanagement#168]

**Comment by gamecss** [comment]
@M1cha @z3ntu

**Comment by M1cha** [comment]
well what kind of documentation are you talking about? what do you want to know?
I didn't write any additional documentation myself and qualcomm doesn't use LK anymore.

**Comment by ghost** [comment]
> well what kind of documentation are you talking about? what do you want to know?
> I didn't write any additional documentation myself and qualcomm doesn't use LK anymore.

like how to create device tree and compile right

**Comment by M1cha** [comment]
you can find the old documentation in the wiki:
https://github.com/efidroid/projectmanagement/wiki/%5BEFIDroid%5D-Build-system/69e6f4cf8a46b08eddb972bcd0b1c93e86689dc3

**Comment by ghost** [comment]
> you can find the old documentation in the wiki: https://github.com/efidroid/projectmanagement/wiki/%5BEFIDroid%5D-Build-system/69e6f4cf8a46b08eddb972bcd0b1c93e86689dc3

but these docs seem not to be applicable to efidroid without lk

**Comment by ghost** [comment]
and how to make arm64 target (with lk version)

**Comment by M1cha** [comment]
IIRC that's not supported. Even 64bit devices used a 32bit LK.
64bit kernels were booted through an SCM call to a higher execution level:
https://github.com/efidroid/bootloader_lk/blob/91bd0e0878af6b6731986519387d17c411482d34/app/aboot/aboot.c#L799

**Comment by ghost** [comment]
> > you can find the old documentation in the wiki: https://github.com/efidroid/projectmanagement/wiki/%5BEFIDroid%5D-Build-system/69e6f4cf8a46b08eddb972bcd0b1c93e86689dc3
> 
> but these docs seem not to be applicable to efidroid without lk

like Porting-a-new-device

**Comment by M1cha** [comment]
Sry I failed to read the issue title properly :P 
The nolk version wasn't anywhere new to being able to boot Android or have enough drivers to support more than the one or two devices we had for testing.

You could take a look at the device port for xiaomi/aries: https://github.com/efidroid/device/tree/xiaomi/aries
Keep in mind that there'll be a ton of missing drivers in https://github.com/efidroid/uefi_edk2packages_EFIDroidPkg though.

You'll definitely need some form of low level debugging like UART to improve on that.
