### ISSUE TITLE
add support for 64-bit qcom devices

### ISSUE THREAD

**Issue by M1cha** [efidroid/projectmanagement#25]
- [x] use 64bit datatypes for addresses in all API calls
- [x] use smem V1 for generating correct memory map's
- [x] boot 64bit kernels via TZ
- [x] make finalize_device script 64bit compatible
- [x] add 64bit support to libsyshook
- [x] add support for 64bit kernel address override

@balika011 is our test dummy :P

**Comment by M1cha** [comment]
all this does work now.

**Comment by M1cha** [comment]
the multiboot userspace still doesn't work for AArch64 devices

**Comment by balika011** [comment]
The grub crashes. (Can't mount any partition.)

**Comment by M1cha** [comment]
64bit devices are fully supported now.
