### ISSUE TITLE
Evaluate if this is even possible

### ISSUE THREAD

**Issue by M1cha** [efidroid/projectmanagement#3]

**Comment by codierae** [comment]
+1 Hardkernel ODroid XU4 http://www.hardkernel.com/main/products/prdt_info.php?g_code=G143452239825 https://github.com/hardkernel/u-boot

**Comment by M1cha** [comment]
while using U-Boot drivers apparently works, we still need to manually implement interrupt and timer support because this is required by UEFI and not supported by U-Boot.

**Comment by codierae** [comment]
any possible ETA with this? or is it even possible to implement in the
hardkernel uboot code - or the codebase their code originates from so they
could just implement the changes from there and then just add their own
changes ontop

**Comment by M1cha** [comment]
well all u have to do is to define the GIC base addresses(we use UEFI's GIC driver anyway) and write a small timer library so the timer interrupt gets fired every few ms.(UEFI needs this for events).

**Comment by M1cha** [comment]
PS: I can't give an ETA since I'm currently working with qemu and don't have a real uboot device.
On qemu I can boot to shell already, but can't type then because of the missing interrupts.

It would be easy to fix but it makes no sense since UEFI natively supports qemu anyway.

**Comment by codierae** [comment]
ODROID/HardKernel is willing to donate uboot hardware to coders if thats
the only hangup

**Comment by M1cha** [comment]
yea that would be great

**Comment by codierae** [comment]
if you go on #odroid on freenode and talk to mdrjr he should be able to get
you what you need - they have a few different uboot boards and ive told him
youll be coming at some point - not sure how many boards they can give up
but they are willing to help out how they can - so whoever would be doing
the uboot code would likely be the best recipient for the first board ;)

**Comment by M1cha** [comment]
we're at the point where EFIDroid doesn't really require it's own UEFI port anymore. this means if U-Boot's efiloader is complete enough you can just load EFIDroidUI.

**Comment by M1cha** [comment]
This doesn't have any real use yet and I'd probably prefer porting uboot code to mainstream LK.
