### ISSUE TITLE
EFIDroid Settings

### ISSUE THREAD

**Issue by feherneoh** [efidroid/projectmanagement#47]
Configuring the EFIDroid UI could be done from the app too. Not replacing the original settings menu, but adding new way to configure it

**Comment by M1cha** [comment]
do we really need this? we're more and more moving to UEFI doing more stuff on it's own(LKL being step1 of that).

While I don't generally disagree it may make both code and UI more complicated than they need to be.

**Comment by saschaelble** [comment]
Make this an app downloadable from efidroidstore?

**Comment by M1cha** [comment]
@saschaelble these apps would run in UEFI, not Android.
Also I don't want to implement this because it doesn't make any sense imo and the app can't really know which options there are(we can't rely on a specific app version being installed either).

closing this now.
