### ISSUE TITLE
create_device error [FP2]

### ISSUE THREAD

**Issue by z3ntu** [efidroid/projectmanagement#56]
Sorry, if this is the wrong repository for this issue, but https://github.com/efidroid/build doesn't have issues enabled.

I tried to create a new device tree for the Fairphone 2.
Build environment is Arch Linux.

> $ create_device boot.img 
Device name (vendor/codename): fairphone/FP2
Device Description (i.e. Moto E): Fairphone 2
LCD Density: 340
Available targets:
  msm7630_surf_nandwrite                  msm8916        mdm9615_nandwrite           msm7630_fusion
                 msm8996                  msm8909     msm7627_6x_nandwrite                  apq8084
                 msm8960 msm7630_fusion_nandwrite                  mdm9615                  mdm9635
                 msm8610   msm7627_surf_nandwrite             msm7627_surf                  mdm9640
                 msm8974                  msm8952                  msm8226                  mdm9625
            msm7630_surf                 msm7627a                  msm8994       msm7627a_nandwrite
              msm7627_6x                  apq8064             msm8660_surf                         
LK Target: msm8974
Error: [Errno 2] No such file or directory: 'out/tmp//boot.img-dt.unlz4'
Traceback (most recent call last):
  File "/mnt/hdd/efidroid/build/tools/create_device", line 198, in <module>
    main(sys.argv[1:])
  File "/mnt/hdd/efidroid/build/tools/create_device", line 180, in main
    if os.path.getsize(BOOTIMGPREFIX+'dt.unlz4')>0:
  File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: 'out/tmp//boot.img-dt.unlz4'

The file `out/tmp/boot.img-dt` exists, but not with the ending `.unlz4`

`boot.img` is available in the following zip at the location `AP/boot.img`: https://storage.googleapis.com/fairphone-updates/d7c72422-62fa-4a19-80af-a2fdd4bee25e/fp2-sibon-16.10.0-manual-userdebug.zip

**Comment by z3ntu** [comment]
Hmm, I worked around it by running `touch out/tmp/boot.img-dt.unlz4`...

**Comment by z3ntu** [comment]
Now, when I try to boot the lk.img file, I get the error message

> $ fastboot boot out/target/fairphone/FP2/lk.img 
downloading 'boot.img'...
OKAY [  0.131s]
booting...
FAILED (remote: bootimage: incomplete or not signed)
finished. total time: 0.132s

I don't really want to flash the file as I have no idea if it is possible to restore my device from a broken LK...

**Comment by M1cha** [comment]
@z3ntu this is the right repo. this repo is a central place for issues and wiki's.
I fixed your problem with the following commit:
https://github.com/efidroid/build/commit/68ab0418db6af8cf3b4ad5abbceb454eab69f745

**Comment by z3ntu** [comment]
Thanks for the quick fix 👍 
For my latter question: Is it possible to recover from a broken little kernel? I don't really want to flash a lk if I don't know if that really works.
I have suspicions because the LK actually loads fastboot and I don't know any other way to flash the LK other than fastboot.

**Comment by M1cha** [comment]
we don't replace the stock bootloader. for testing development versions we use fastboot boot only.
for installing it permanently we flash uefi_boot.img to the boot partition and uefi_recovery.img to the recovery partition.

**Comment by z3ntu** [comment]
The problem is, that the bootloader for my phone has a bug, that "fastboot boot" doesn't work with the fastboot error I wrote above.
IRC log from a developer and me:

> [16:43] <z3ntu> part: do you know if it is possible to boot up an img with "fastboot boot"? I get the error "FAILED (remote: bootimage: incomplete or not signed)"
[16:46] <part> z3ntu: Let me check
[16:54] <z3ntu> part: I even get the error with the boot.img from the package fp2-sibon-16.10.0-manual-userdebug
[16:56] <part> z3ntu: I get the same
[16:56] <part> [224940] fastboot: download:0064d800
[16:56] <part> [225150] fastboot: boot
[17:01] <part> I hadn't tried it
[17:02] <part> hadn't tried it before, I mean
[17:04] <part> http://code.fairphone.com/gerrit/gitweb?p=fp2-dev/kernel/lk.git;a=blob;f=app/aboot/aboot.c;h=37e2a721f8b7a4ca803f61bf54598bb495c728b5;hb=refs/heads/fp2-sibon#l1548

Guess I'll have to wait until it gets fixed :/

**Comment by M1cha** [comment]
just flash it to your recovery or boot partition then. if it doesn't work you can just reflash the correct boot.img or recovery.

btw: fp2 has official public sources including the bootloader? I gotta take a look at that.

**Comment by z3ntu** [comment]
Yes, they have a ROM called "FP Open" which is 99% open source what means that you can build it yourself but it still contains those nasty binary blobs. :/ And the release of "FP Open" is mostly at least half a month behind the GMS (Google Mobile Services) ROM which contains many fixes earlier. Also their ROM has many weird bugs such as that the OS isn't able to set the hardware clock (probably a kernel issue) and many other weird bugs / "features" ;)

**Comment by z3ntu** [comment]
So I have managed to get efidroid working (had to sign the lk.img file) but it doesn't show neither android nor the recovery... any idea? maybe I have missed some wiki page.

**Comment by M1cha** [comment]
that's normal because since efidroid is supposed to be installed on all kernel partitions they would never contain anything useful anyway - so they are ignored.

if you boot to recovery from within efidroid once, he'll create the redirection images on the esp which you can flash to using dd then.

What you've missed from the guide is the local otaserver part.
What I've just explained is a workaround so you don't have to install using the app. If you ever want to test multibooting without manually creating rom's then you have to setup a local ota server anyway.

**Comment by z3ntu** [comment]
I have already got the OTA server working. So you mean I should boot uefi_recovery.img ?

**Comment by z3ntu** [comment]
Another question: The variable `$TARGET_GRUB_KERNEL_OUT` is apparently never set (is only used in `build/uefiappconfigs/grub/grub.sh`) but is used for several commands. Is there anything wrong in my environment?

**Comment by z3ntu** [comment]
And something in the app crashes and therefore fails to work correctly

> 10-28 10:11:08.115 9622-9831/org.efidroid.efidroidmanager W/System.err: java.lang.InterruptedException
10-28 10:11:08.115 9622-9831/org.efidroid.efidroidmanager W/System.err:     at java.lang.Object.wait(Native Method)
10-28 10:11:08.115 9622-9831/org.efidroid.efidroidmanager W/System.err:     at java.lang.Object.wait(Object.java:422)
10-28 10:11:08.115 9622-9831/org.efidroid.efidroidmanager W/System.err:     at org.efidroid.efidroidmanager.RootToolsEx.commandWait(RootToolsEx.java:52)
10-28 10:11:08.115 9622-9831/org.efidroid.efidroidmanager W/System.err:     at org.efidroid.efidroidmanager.RootToolsEx.getBlockDevices(RootToolsEx.java:219)
10-28 10:11:08.118 9622-9831/org.efidroid.efidroidmanager W/System.err:     at org.efidroid.efidroidmanager.activities.MainActivity$1.doInBackground(MainActivity.java:94)
10-28 10:11:08.118 9622-9831/org.efidroid.efidroidmanager W/System.err:     at org.efidroid.efidroidmanager.activities.MainActivity$1.doInBackground(MainActivity.java:85)
10-28 10:11:08.118 9622-9831/org.efidroid.efidroidmanager W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
10-28 10:11:08.118 9622-9831/org.efidroid.efidroidmanager W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-28 10:11:08.118 9622-9831/org.efidroid.efidroidmanager W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
10-28 10:11:08.118 9622-9831/org.efidroid.efidroidmanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-28 10:11:08.118 9622-9831/org.efidroid.efidroidmanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-28 10:11:08.119 9622-9831/org.efidroid.efidroidmanager W/System.err:     at java.lang.Thread.run(Thread.java:818)

(maybe the lines are off by one or two because I have added some debug code to find out why it crashes)

**Comment by z3ntu** [comment]
Oh okay, after I have installed efidroid via the app Android and the recovery shows up, so that's not a problem anymore

**Comment by z3ntu** [comment]
Oh yeah and the volume down button doesn't work, only the volume up and the power button (the phone also has a camera button but I don't think there would be any usefulness just for this phone to do something with that button)

**Comment by M1cha** [comment]
- recovery as in TWRP, not uefi_recovery, it would create the ESP too(like installing from the app would)
- there are many unused variables since most of them are auto generated :) grub isn't used at all in this project
- the java warning is normal
- #54 won't help you since I assume that UEFI doesn't show you an error message, that ticket is for providing more information, not adding more debug abilities
- you have to fix the input devices using lkshim, the camera button would be very useful as a back button. lkshim example: https://github.com/efidroid/device/tree/motorola/thea/lkshim

**Comment by z3ntu** [comment]
Thanks for your help until now, but the msm8974 platform thingy doesn't have a method similar to [`gpio_status`](https://github.com/efidroid/bootloader_lk/blob/qcom/LA.BF64/platform/msm8974/include/platform/gpio.h), see [here](https://github.com/efidroid/bootloader_lk/blob/qcom/LA.BF64/platform/msm8974/include/platform/gpio.h) so I don't know how to access the GPIO with that.

**Comment by M1cha** [comment]
ofc it does: https://github.com/efidroid/bootloader_lk/blob/qcom/LA.BF64/target/msm8974/init.c#L116

**Comment by z3ntu** [comment]
So I should copy and modify that function in this init.c file?

**Comment by M1cha** [comment]
yes, voldown uses pmic resin by default, just use gpio for that too.

**Comment by z3ntu** [comment]
Thanks, volume down now works :) (also thanks to the [fairphone lk](https://github.com/FairphoneMirrors/android_kernel_lk_fairphone_fp2/blob/fp2-sibon/target/FP2/init.c#L162)). Now is there any way to get the dmesg in efidroid? I didn't find any useful command with `fastboot oem help`

**Comment by M1cha** [comment]
you can get the dmesg the usual way: cat /proc/last_kmsg
If you phone doesn't support pram or your kernel has lastkmsg disabled you're pretty much out of luck.

Can you try to boot without ramdisk patching? if that works we at least know that the kernel technically boots and that it's a multiboot problem only.

**Comment by z3ntu** [comment]
Booting with an unpatched ramdisk (holding power long on Android and confirming) goes back to efidroid as before...
So tried the following right now: efidroid -> boot android -> goes back to efidroid -> rebooting to bootloader -> fastboot boot recovery.img -> getting /proc/last_kmsg which got me [this](http://pastebin.com/gc4mZd3j) but I am quite sure that's the last_kmsg one boot too late. Is it possible to create an option which copies last_kmsg to the sd card or something on each bootup? that would help incredibly.

**Comment by M1cha** [comment]
@z3ntu that's actually the dmesg from the previous android boot(so it's "one too early).
What this means is that there's a "low level" booting problem and that you can stop testing patched boot now until we fixed unpatched boot. Also I recommend testing with unpatched recovery since it's a much less sensitive environment.

please run fastbootwrapper oem dump-atags atags.bin from within lk.img and send me the resulting lk.img. you may want to send me that in slack or an e-mail because it may contain serial numbers.

**Comment by z3ntu** [comment]
for anyone other than @M1cha and me: we continued the conversation on slack :)

**Comment by M1cha** [comment]
for everybody else: there was a problem which caused UEFI to not shut down the LCD.
I fixed that but z3ntu doesn't need that anyway since he can use the 2ndstage driver with the dma trigger enabled.
