### ISSUE TITLE
Efidroid app Xiaomi mi2s

### ISSUE THREAD

**Issue by Roysten** [efidroid/projectmanagement#59]
I cannot install efidroid for the Xiaomi mi2s, the info.json file does not exist...
https://raw.githubusercontent.com/efidroid/ota/master/xiaomi/aries/info.json

It is a shame, would love to try this great project :)

**Comment by Roysten** [comment]
The app is stuck at the following screen:
![image](http://imgur.com/g0m43Qv)

**Comment by M1cha** [comment]
I didn't enable the OTA server for this device yet because I couldn't figure out some major problems with booting MIUI.

**Comment by Roysten** [comment]
I see. Xiaomi doing some weird/non-standard stuff?

Maybe it is a good idea to show the supported devices in the app or at the very least put it in the app description on Google Play.

**Comment by M1cha** [comment]
@Roysten usually devices without support can't even open the app but since I started developing on mi2, it has a ota entry already. Sorry about that.
