### ISSUE TITLE
User-friendliness and Developer-friendliness improvements proposals

### ISSUE THREAD

**Issue by Arvil** [efidroid/projectmanagement#65]
- [ ] Make the download repository able to be optionally changed (so that dev builds are easier to deploy, because using the adb root shell to modify one of the app's variable is counter intuitive)
- [ ] Add a simple text message after the device has been successfully created to say `You can now reboot into UEFI, select the recovery then point to your newly created device configuration to install your ROM` could be enough to not be unsettling for the newcomer.
- [ ] Have clear specifications on how to use EFIDroid when debugging a ROM, like can I retrieve `/proc/last_kmsg` from UEFI, does it get erased in favor of LK's one when I boot into the recovery ?
- [ ] Provide an alternative way than GPlay for downloading the app. An [F-Droid](https://f-droid.org/) custom repo or self-updating app (typically with a folder on the server with the latest apk and a file containing its version for comparison) could do it.
- [ ] Also I think in Google guidelines an app is not supposed to to loop on a modal window (like it does in EFIDroid when the device is not found on the server) but inform it failed with a modal window then switch back on a normal window with the option to try again (sorry for not using Android standard verbiage I don't know much about it) like what is done in the Xposed Framework installer (will try to post images later)

**Comment by z3ntu** [comment]
3. See #42 
4. You don't have adb access in the UEFI so you can't pull it there. See #54 
5. Already asked @M1cha 👍  https://f-droid.org/forums/topic/efidroid/

**Comment by Arvil** [comment]
1. OK removed the duplicate, failed to find it somehow when writing this.
2. The question was more about whether I had to pull it from UEFI or Recovery (pulling or copying it might then be implemented in EFIDroid's file manager).
3. I proposed DDL and _custom_ F-Droid because of the rapid development circle and the fact F-Droid is not always very reactive to new versions (IIRC) because of their strict policies which might hinder deployment of new versions if any of their conditions are broken. Also would allow for separate channels stable/beta if need be which would get rid of the tagging problem.

**Comment by M1cha** [comment]
> Have clear specifications on how to use EFIDroid when debugging a ROM, like can I retrieve /proc/last_kmsg from UEFI, does it get erased in favor of LK's one when I boot into the recovery ?
first off, that log is in RAM, it's not a real file. Also that's a linux feature. Neither LK nor UEFI know about this.

> Provide an alternative way than GPlay for downloading the app. An F-Droid custom repo or self-updating app (typically with a folder on the server with the latest apk and a file containing its version for comparison) could do it.
the official XDA thread has download links(atm they're not up2dat though) I'm working on F-Droid

> Also I think in Google guidelines an app is not supposed to to loop on a modal window (like it does in EFIDroid when the device is not found on the server) but inform it failed with a modal window then switch back on a normal window with the option to try again (sorry for not using Android standard verbiage I don't know much about it) like what is done in the Xposed Framework installer (will try to post images later)
I could use a fullscreen overlay instead of the window, but allowing to use any part of the app just can't be done.

**Comment by M1cha** [comment]
the app will go away.
