### ISSUE TITLE
Fails to get selinux context in twrp

### ISSUE THREAD

**Issue by saschaelble** [efidroid/projectmanagement#67]
Note 3
twrp 3.0.2-1
patched boot

Recovery.log
I:Copying file /cache/recovery/log to /cache/recovery/last_log
tw_get_context failed to get selinux context
I:Failed to get default contexts and file mode for storage files.

**Comment by M1cha** [comment]
is that even a bug? Verify if that happens with unpatched boot too.

**Comment by saschaelble** [comment]
This is not present in unpatched boot. It is a bug:
Unpatched:
I:Copying file /cache/recovery/log to /cache/recovery/last_log
tw_get_context got selinux context: u:object_r:media_rw_data_file:s0
I:Got default contexts and file mode for storage files.

**Comment by M1cha** [comment]
this may be related to your previous bug because in case the cache partition can't be mounted all the files land on the rootfs - which doesn't support selinux contexts.
