### ISSUE TITLE
add support for preventing write-access to fstab.multiboot

### ISSUE THREAD

**Issue by M1cha** [efidroid/projectmanagement#71]

**Comment by feherneoh** [comment]
My idea would be using images created by truncating on a ramdisk to fake the partition

**Comment by M1cha** [comment]
@feherneoh yes that was my idea too.

the funny thing is that it's been just a few weeks since I made the redirection code very flexible.
Without that this issue would have been a lot of work :D

**Comment by M1cha** [comment]
couldn't we even just prevent write-access to ALL partitions except for the multiboot ones?
all changes outside the multiboot parts would be global and a multiboot rom should never be able to make global changes.

I'd exclude /data/media and non-internal devices like sdcard's though.

**Comment by M1cha** [comment]
fixed with https://github.com/efidroid/modules_multiboot/commit/fdd4fc66030c8987eaf4092eba7b885e9ef9f2d3
