### ISSUE TITLE
SuperSU issue

### ISSUE THREAD

**Issue by muertead** [efidroid/projectmanagement#73]
Hi roms (Tugapower N9 and earlier realeses) with SuperSU preinstaled does not boot,  it restarts from selection screen/menu and again goes back to selection/menu. Roms without SuperSU boots normaly,  but it has superuser preinstaled, si I tried to flash SuperSU (stable and/or beta realeses) and the rom does not boot it restarts (tried with cm14.1 nightlies,  Resurrection Remix). My device OPO,  COS13.1.2.

**Comment by M1cha** [comment]
1) always post the error messages that are shown after a reboot
2) this should have been fixed already but the 1+1 build hasn't been updated yet.

**Comment by muertead** [comment]
I would show error message,  but there are no any. Ok I shall wait for updated build for my device

**Comment by xakep666** [comment]
It`s a problem with file_contexts parsing. I member that @M1cha already fixed it. I tried to boot this rom with efidroid compiled from fresh sources. Rom booted up successfully.

**Comment by M1cha** [comment]
yes but u saw an error message. It's weird that he doesn't.
Also I've just downloaded 'Tugapower N9' and file_contexts.bin is a binary, not a text file.

**Comment by xakep666** [comment]
SuperSU decompiles file_contexts.bin in systemless installation mode (makes it text and applies patch). So problem source is not a rom.

**Comment by M1cha** [comment]
well but as I said. I check his ROM and file_contexts.bin is a binary file, not a text file.

**Comment by M1cha** [comment]
@muertead pls try again with the new build and report back

**Comment by muertead** [comment]
Thanks for the new build, but now if I want to enter recovery I get Error: "Unable to find suitable device tree for device (208/0x00010001/0x00010108/0). Press Ok then get Error :" tagloader 'qcdt'(2) returned -1. Press OK and want to boot to my official rom and get the same Errors. How can I go back (except of course for doing reset of all system, dont realy know how to do it, if I cannot enter recovery, but I will find).

**Comment by M1cha** [comment]
sounds like @xakep666 got more work todo :P I guess for now you either have to use an old version( https://github.com/efidroid/files/releases/download/builds/otapackage-20161110-oneplus_bacon.zip ) or wait until he fixed the device.

**Comment by muertead** [comment]
Imanaged to get back to my internal rom by flashing twrp 2.8.7.0 over previuos tuga twrp 3.03.0, and flashed internal rom again. And everything is ok, no data lost. Wait for fix 😂

**Comment by M1cha** [comment]
@muertead can you 'fastboot boot' this file and send me the output of fastboot oem lk_log?
https://transfer.sh/2qVYz/lk.img

**Comment by muertead** [comment]
I am not developer so if I will do something wrong don't be mad. I will try to tomorrow. P. S.  I have never did the fastboot boot.

**Comment by M1cha** [comment]
@muertead sbd. else who had the same issue ran the tests for me already and I found a possible solution, so you don't have to become a developer :P

**Comment by muertead** [comment]
Ok. Still wait for stable realese😉

**Comment by M1cha** [comment]
@muertead a new build is out for you to test :)

**Comment by muertead** [comment]
Hi. Everything works great. Tested roms: TugapowerN10, Resurrection Remix newest build, CM14.1 latest. SuperSu 2.78 sr5. Roms booted after second atempt, first time restarted to selection menu of efidroid, second time booted succesfully. Also opengapps nano booted succesfully with twrp 3020. Other twrps (tuga 3033, twrp 2.8.7.0) got error 2.
Thanks for the build.

**Comment by M1cha** [comment]
can you tell me the exact error message shown when booting "other twrps"?

**Comment by muertead** [comment]
Sorry. I tried now on twrp tuga 3033, and it flashed good. Will test more and if I get error,  will post.

**Comment by M1cha** [comment]
I'm closing this then since this talk is not related to supersu anymore. If you have more problems, create new tickets.
