### ISSUE TITLE
HTC One M8 (GPE) Support

### ISSUE THREAD

**Issue by npjohnson** [efidroid/projectmanagement#84]
ARCH: MSM8974
OEM: HTC
Branch used to build: LA.BF64

LK builds fine, and boots with no display. If I used the display DTB option, display works just fine.

UEFI builds fine, but whether booted or flashed to the Boot partition, UEFI doesn't initialize, and it hangs at the Google (aboot) logo. While hung at the Google logo, I can see the device with fastboot over USB, but any attempt at executing a fastboot command results in  "..." being returned (to imply fastboot is waiting on a response), then the device panics and reboots.

I am on the GPE firmware, but this issue likely persists on the Sense firmware, as the only major changes are partition table layout/partition sizes.

**Comment by M1cha** [comment]
sounds like you have two problems:
- uefi fails to initialize the scren and falls back to fastboot mode
- fastboot is broken

**Comment by z3ntu** [comment]
I already tried porting efidroid to the HTC One M8 (device from a friend of mine) but I believe I had similar issues. That's the configuration I had: [m8.zip](https://github.com/efidroid/projectmanagement/files/827102/m8.zip)

**Comment by npjohnson** [comment]
No progress on this port. I'm stuck.

**Comment by shirokatze** [comment]
Huh, funny. Mine doesn't boot the uefi img at all. It hangs before rebooting to system.
Like yours, LK works just fine

**Comment by npjohnson** [comment]
No progress this week.
