### ISSUE TITLE
Verizon Samsung Galaxy S4 Support

### ISSUE THREAD

**Issue by npjohnson** [efidroid/projectmanagement#85]
ARCH: MSM8960 (actually apq8064t, but msm8960 build target)
OEM: Samsung
Branch used to build: LA.BF64

NOTE: This device requires all images to be LOKI'd. The good news is that LK/UEFI both get along with LOKI's weird loading address trickery.

LK builds fine, and boots with display. 

UEFI builds fine, and boots to the selection menu, with buttons fully functional! I am, however, unable to boot the internal OS (Lineage OS 14.1), which is (I believe) due to the issue @gabixdev mentioned multiple times (here: https://github.com/efidroid/projectmanagement/issues/80), it seems to be some sort of kernel compression issue, as LZMA packed kernels work fine, but XZ'd/GZIP'd kernels fail to load with an error like "Cant find tagloader for type RAW (-1)".

Currently, to install using EFIDroid's app, one must set up the local OTA server, install, the dd out boot & recovery, LOKI them, then dd them back to the boot & recovery partitions respectively.

Oddly, if I manually select the boot.img using EFI Droid's file browser, I am able to boot XZ'd/GZIP'd kernels as well as LZMA'd kernels.

Another interesting note, and separate issue is that the EFI Droid app seems to have a hardcoded /dev/block/platform/*/by-name/modem as the /firmware mount for EFI Droid, but the S4 has two, neither of which is labeled "modem". We have apnhlos ==> /firmware * mdm ==> /firmware-mdm. The reason I say this is that when I attempt to use the EFI Droid app to add a ROM, I get "Error: /dev/block/platform/msm_sdcc.1/by-name/modem not found." I even went as far as to define both of the above partitions in my multiboot.fstab as opposed to the original modem entry.

**Comment by M1cha** [comment]
about the modem issue: did you wipe the app's data after changing the fstab?
None of the paths should be hardcoded but the app heavily caches fstab and device info.

**Comment by npjohnson** [comment]
I will tonight.

**Comment by npjohnson** [comment]
To update on this device's port, it boots to UEFI, but just as the Note 3 and 4 did after installing the OTA package using a local OTA server, then dd'ing out, LOKI'ing the images, and re'dd'ing in boot & recovery, the EFI Droid app displays "EFI Droid has ESP backup of boot and recovery, but not installed" (or something along those lines).

I think EFI Droid has some issue on Samsung devices. I'll wait for confirmation to start another issue.

The images efidroid places in the ESP are both of the same size (10 MB), and don't boot. If I manually place my boot and recovery image in the ESP folder, it boots fine, if I don't, the images efidroid placed there result in "can't find taggloader for type RAW -1". 

Also, no LOKI'd boot or recovery image will boot through EFI droid... due to the fact that every ROM for jfltevzw is built with LOKI'd boot and recovery images, this needs to be fixed in UEFI.

**Comment by npjohnson** [comment]
Okay, this port has some oddities.

With Lineage OS as the Internal, and by manually placing twrp and boot (un-LOKI'd) in UEFIESP we are able to boot the OS! But the same can't be said for TWRP, which only boots with no ramdisk patching :/

**Comment by M1cha** [comment]
if UEFI shows "last boot failed" errors pleas post the exact error messages. If your kernel/devices supports it you can also dump a lastkmsg/ramoops.
But you probably want to run this before booting:
fastboot oem setnvvar multiboot-debuglevel 0

**Comment by npjohnson** [comment]
We're able to boot the OS, but upon booting TWRP with ramdisk patching, we get a reboot and an error of "Last boot failed: init returned."

**Comment by sub77** [comment]
same problem on samsung t530, booting official twrp 3.1.0-0 from twrp.me is working fine, other ones: last boot failed: init returned.
