### ISSUE TITLE
Pixel/Pixel XL Support

### ISSUE THREAD

**Issue by npjohnson** [efidroid/projectmanagement#86]
ARCH: MSM8996
OEM: "Google" (HTC)
Branch used to build: LA.UM

Whether booted or flashed to the Boot partition, LK doesn't initialize, and it hangs at the Google (aboot) logo. No LK access over USB.

This is likely due to the looming "LK doesn't boot on 64-bit devices" we don't understand yet.

**Comment by GabrielTK** [comment]
+1

**Comment by npjohnson** [comment]
My XL is locked right now, but I will attempt M1cha's manually appended FDT method when I next decide to unlock the device.

**Comment by GabrielTK** [comment]
Wait... Sorry, my XL is locked too. What do you mean with M1cha's manually appended FDT method??

On Mar 13, 2017 7:35 PM, "Nolen Johnson" <notifications@github.com<mailto:notifications@github.com>> wrote:

My XL is locked right now, but I will attempt M1cha's manually appended FDT method when I next decide to unlock the device.

**Comment by M1cha** [comment]
@GabrielTK https://github.com/efidroid/projectmanagement/issues/89#issuecomment-286063675

**Comment by GabrielTK** [comment]
Oh, ok. I thought it was another way to unlock Pixel Devices.

Also, I know this might me a bit off topic, but, do you know any app like BootUnlocker that works in Pixel (for locking the bootloader with root)?

On Mar 15, 2017 6:52 AM, "Michael Zimmermann" <notifications@github.com<mailto:notifications@github.com>> wrote:

@GabrielTK<https://github.com/GabrielTK> #89 (comment)<https://github.com/efidroid/projectmanagement/issues/89#issuecomment-286063675>

**Comment by npjohnson** [comment]
No progress this week.
