### ISSUE TITLE
Lenovo Vibe K5 uefi make fail

### ISSUE THREAD

**Issue by rrgreatvijay5** [efidroid/projectmanagement#87]
Device: Lenovo Vibe K5
Snapdragon 415
RAM: 2GB
msm8929

So nouefi lk.img booted fine and i finalized the device
But when i make uefi build, it fails..

`/home/frosty/out/target/arm/uefiapp_LKL/EFIDroidUEFIApps/LKL/LKL.c: In function 'LKLEntryPoint':
/home/frosty/out/target/arm/uefiapp_LKL/EFIDroidUEFIApps/LKL/LKL.c:97:41: error: passing argument 2 of 'lkl_start_kernel' makes pointer from integer without a cast [-Werror=int-conversion]
ret = lkl_start_kernel(&lkl_host_ops, 64 * 1024 * 1024, "");
^~
In file included from /home/frosty/out/target/arm/uefiapp_LKL/EFIDroidLKL/include/lkl_host.h:8:0,
from /home/frosty/out/target/arm/uefiapp_LKL/EFIDroidUEFIApps/LKL/LKL.h:55,
from /home/frosty/out/target/arm/uefiapp_LKL/EFIDroidUEFIApps/LKL/LKL.c:24:
/home/frosty/out/target/arm/uefiapp_LKL/EFIDroidLKL/include/lkl/asm/host_ops.h:141:5: note: expected 'const char *' but argument is of type 'int'
int lkl_start_kernel(struct lkl_host_operations *lkl_ops,
^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [/home/frosty/out/target/arm/uefiapp_LKL/Build/EFIDroidUEFIApps/DEBUG_GCC5/ARM/EFIDroidUEFIApps/LKL/LKL/OUTPUT/LKL.obj] Error 1
GNUmakefile:4224: recipe for target '/home/frosty/out/target/arm/uefiapp_LKL/Build/EFIDroidUEFIApps/DEBUG_GCC5/ARM/EFIDroidUEFIApps/LKL/LKL/OUTPUT/LKL.obj' failed
make[2]: Leaving directory '/home/frosty/out/target/arm/uefiapp_LKL/Build/EFIDroidUEFIApps/DEBUG_GCC5/ARM/EFIDroidUEFIApps/LKL/LKL'

build.py...
: error 7000: Failed to execute command
make tbuild [/home/frosty/out/target/arm/uefiapp_LKL/Build/EFIDroidUEFIApps/DEBUG_GCC5/ARM/EFIDroidUEFIApps/LKL/LKL]
	CC mklost+found.c
	CC filefrag.c
	CC e2freefrag.c
	CC uuidd.c

build.py...
: error F002: Failed to build module
/home/frosty/out/target/arm/uefiapp_LKL/EFIDroidUEFIApps/LKL/LKL.inf [ARM, GCC5, DEBUG]

- Failed -
Build end time: 01:42:30, Mar.08 2017
Build total time: 00:08:26
`

Any help on this?

**Comment by M1cha** [comment]
you just need to repo sync. I've fixed that error yesterday.

**Comment by rrgreatvijay5** [comment]
Ok so a new issue
lk is booting fine now..
but when i try to boot uefi then this shows up..
Attached a screenshot for that.
Any fix? @M1cha 
![img_20170310_191913_hdr](https://cloud.githubusercontent.com/assets/13448335/23798040/c1ffc24c-05c8-11e7-8852-6cdb864b1151.jpg)

**Comment by Shr3ps** [comment]
Same state here:

![img_20170328_155135300_hdr](https://cloud.githubusercontent.com/assets/1845672/24408799/f429de6a-13ce-11e7-9b56-3c0d22207252.jpg)

**Comment by M1cha** [comment]
we're not using LK anymore.
