### ISSUE TITLE
[OnePlus 3T] dtb_panel_reader.o missing?

### ISSUE THREAD

**Issue by Glove007** [efidroid/projectmanagement#88]
When I compiled NOUEFI variant of LK for the OnePlus 3T with the default display driver _DISPLAY_2NDSTAGE_ and tried to fastboot boot it, there was the error "**FAILED (remote: dtb not found)**". Because of this error I tried to choose _DISPLAY_2NDSTAGE_DTB_ as display driver so I replaced "DISPLAY_2NDSTAGE := 1" with "DISPLAY_2NDSTAGE_DTB := 1" in the lk-inc.mk. Was that right...? Because when I tried to compile LK again, it gives me the error "**arch/arm/compile.mk:3: recipe for target '/home/.../dev/out/device/OnePlus/OnePlus3T/lk_kernel/build-msm8996//home/.../dev/bootloader/lk/common/shared/lib/2ndstage_display_dtb/dtb_panel_reader.o' failed**", so I looked the file _bootloader/lk/common/shared/lib/2ndstage_display_dtb/dtb_panel_reader.o_ up and found out that it's not there. There is only the file _dtb_panel_reader.c_.

Why is this file missing and how can I compile LK with the display driver _DISPLAY_2NDSTAGE_DTB_?

**Comment by M1cha** [comment]
I'm not sure why you are seeing that compilation error but the fastboot error is not related to the screen so you don't need to change that option.

try to add 'BOOTIMG_DT_KEEP_NODES = 1' in your config.ini

**Comment by Glove007** [comment]
I tried to add the mentioned string in my config.ini but I still get the same fastboot error. What means this error?

**Comment by M1cha** [comment]
it means that the bootloader thinks that the boot image is incompatible.
try to use lk_origdtb.img (that's a workaround, not a fix)

**Comment by Glove007** [comment]
Booting was okay now, but now it shows me a black screen. The device must be somehow powered on, because I have to long press the power button to reboot it...
