### ISSUE TITLE
Samsung Devices Don't Show EFI Droid as Installed.

### ISSUE THREAD

**Issue by npjohnson** [efidroid/projectmanagement#94]
The EFI Droid app installs the otapackage from the local OTA server, but shows that EFI Droid is not installed, saying something along the lines of "ESP has backup of boot and recovery but EFI Droid is not installed". This happens on both the S4, and the Note 3/4.

Not sure how to debug this one... it may be why the S4 is unable to boot the images EFI Droid places in the ESP folder.

**Comment by M1cha** [comment]
this has been fixed with:
https://github.com/efidroid/android_app_efidroidmanager/commit/70b5b38492627b88a55b75c3959eb9daa3853680

I didn't update the playstore app yet, sry
