### ISSUE TITLE
Build fails on Arch Linux error: "yywrap" redefined [-Werror]

### ISSUE THREAD

**Issue by shirokatze** [efidroid/projectmanagement#95]
> Makefile targets are not yet supported (modules/selinux_7)
> Makefile targets are not yet supported (modules/selinux_7)
> Makefile targets are not yet supported (modules/selinux_6)
> Makefile targets are not yet supported (modules/selinux_6)
> Buildtype: DEBUG
> Device: oneplus/bacon
> Architectures: arm
> Configuring for host, target, device
> make[1]: Entering directory '/home/felis/Projects/efidroid'
> Compiling host_dtc
> make[2]: Entering directory '/home/felis/Projects/efidroid/out/host/dtc/dtc'
> ....
> 	 CC convert-dtsv0-lexer.lex.o
> convert-dtsv0-lexer.lex.c:398:0: error: "yywrap" redefined [-Werror]
>  
>  
> convert-dtsv0-lexer.lex.c:74:0: note: this is the location of the previous definition
>  
>  
> cc1: all warnings being treated as errors
> make[2]: *** [Makefile:256: convert-dtsv0-lexer.lex.o] Error 1
> make[2]: Leaving directory '/home/felis/Projects/efidroid/out/host/dtc/dtc'
> make[1]: *** [out/build.mk:703: host_dtc] Error 2
> make[1]: Leaving directory '/home/felis/Projects/efidroid'
> 
> #### make failed to build some targets (4 seconds) ####
> 
The output was shortened a little bit.
Followed the steps [getting started](https://github.com/efidroid/projectmanagement/wiki/[EFIDroid]-Getting-Started) . Tried porting to a new device as well as compiling for existing device. Both had the same error.

**Comment by z3ntu** [comment]
Install flex 2.6.1 or compile the newest version from git master. There's also the possibility that you put the binary of either flex 2.6.1 or the newest git master version into `build/tools/`.

**Comment by shirokatze** [comment]
currently on version 2.6.3. No flex binaries inside build/tools/

**Comment by z3ntu** [comment]
`rm -rf out` is always good when stuff changes :)
