### ISSUE TITLE
Galaxy S4 (i9505) Support

### ISSUE THREAD

**Issue by alula** [efidroid/projectmanagement#96]
ARCH: APQ8064T
OEM: Samsung
Branch used to build: LA.BF64

Everything seems to work fine (buttons, display etc.)
The only issue is (stock) rom kernel booting: #80 

Needs also to be tested with 4.2.2 non/knox bootloader, but it will probably work...

https://github.com/alula/device/tree/samsung/jflte

**Comment by npjohnson** [comment]
@gabixdev I can confirm it works on non-KNOX Bootloaders, as jfltevzw actually requires Pre-KNOX Bootloaders to run custom boot images, haha.
